<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>sigecoom_wcf_proxies</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\SIGECOM\SIGECOM\Service References\GuiaRemisionService\Reference.vb">
      <Link>Service References\GuiaRemisionService\Reference.vb</Link>
    </Compile>
  </ItemGroup>

</Project>
