'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ListaClienteCabService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ListaClienteCab", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ListaClienteCab
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClienteField As ListaClienteCabService.Cliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As ListaClienteCabService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoListaPrecioClienteField As ListaClienteCabService.EstadoListaPrecioCliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecRegistroField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecVencimientoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdListaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonedaField As ListaClienteCabService.Moneda
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumContratoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cliente() As ListaClienteCabService.Cliente
            Get
                Return Me.ClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClienteField, value) <> true) Then
                    Me.ClienteField = value
                    Me.RaisePropertyChanged("Cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As ListaClienteCabService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoListaPrecioCliente() As ListaClienteCabService.EstadoListaPrecioCliente
            Get
                Return Me.EstadoListaPrecioClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoListaPrecioClienteField, value) <> true) Then
                    Me.EstadoListaPrecioClienteField = value
                    Me.RaisePropertyChanged("EstadoListaPrecioCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecRegistro() As Date
            Get
                Return Me.FecRegistroField
            End Get
            Set
                If (Me.FecRegistroField.Equals(value) <> true) Then
                    Me.FecRegistroField = value
                    Me.RaisePropertyChanged("FecRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecVencimiento() As Date
            Get
                Return Me.FecVencimientoField
            End Get
            Set
                If (Me.FecVencimientoField.Equals(value) <> true) Then
                    Me.FecVencimientoField = value
                    Me.RaisePropertyChanged("FecVencimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdLista() As Integer
            Get
                Return Me.IdListaField
            End Get
            Set
                If (Me.IdListaField.Equals(value) <> true) Then
                    Me.IdListaField = value
                    Me.RaisePropertyChanged("IdLista")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Moneda() As ListaClienteCabService.Moneda
            Get
                Return Me.MonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonedaField, value) <> true) Then
                    Me.MonedaField = value
                    Me.RaisePropertyChanged("Moneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumContrato() As String
            Get
                Return Me.NumContratoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumContratoField, value) <> true) Then
                    Me.NumContratoField = value
                    Me.RaisePropertyChanged("NumContrato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApeMatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApePatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AprCliField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiaPagoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DniCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DueCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As ListaClienteCabService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecIngField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraPagoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LimiteCreditoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ListaCliField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonedaField As ListaClienteCabService.Moneda
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumCtaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObsCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SectorClienteField As ListaClienteCabService.SectorCliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoClienteField As ListaClienteCabService.TipoCliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoContribuyenteField As ListaClienteCabService.TipoContribuyente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoIdField As ListaClienteCabService.TipoDocumentoId
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoMedioContactoField As ListaClienteCabService.TipoMedioContacto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UrlCliField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrCli() As String
            Get
                Return Me.AbrCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrCliField, value) <> true) Then
                    Me.AbrCliField = value
                    Me.RaisePropertyChanged("AbrCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApeMat() As String
            Get
                Return Me.ApeMatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApeMatField, value) <> true) Then
                    Me.ApeMatField = value
                    Me.RaisePropertyChanged("ApeMat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApePat() As String
            Get
                Return Me.ApePatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApePatField, value) <> true) Then
                    Me.ApePatField = value
                    Me.RaisePropertyChanged("ApePat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AprCli() As Boolean
            Get
                Return Me.AprCliField
            End Get
            Set
                If (Me.AprCliField.Equals(value) <> true) Then
                    Me.AprCliField = value
                    Me.RaisePropertyChanged("AprCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesCli() As String
            Get
                Return Me.DesCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesCliField, value) <> true) Then
                    Me.DesCliField = value
                    Me.RaisePropertyChanged("DesCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DiaPago() As String
            Get
                Return Me.DiaPagoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DiaPagoField, value) <> true) Then
                    Me.DiaPagoField = value
                    Me.RaisePropertyChanged("DiaPago")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DniCli() As String
            Get
                Return Me.DniCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DniCliField, value) <> true) Then
                    Me.DniCliField = value
                    Me.RaisePropertyChanged("DniCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DueCli() As String
            Get
                Return Me.DueCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DueCliField, value) <> true) Then
                    Me.DueCliField = value
                    Me.RaisePropertyChanged("DueCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As ListaClienteCabService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As Integer
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Me.EstadoField.Equals(value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxCli() As String
            Get
                Return Me.FaxCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxCliField, value) <> true) Then
                    Me.FaxCliField = value
                    Me.RaisePropertyChanged("FaxCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecIng() As Date
            Get
                Return Me.FecIngField
            End Get
            Set
                If (Me.FecIngField.Equals(value) <> true) Then
                    Me.FecIngField = value
                    Me.RaisePropertyChanged("FecIng")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraPago() As String
            Get
                Return Me.HoraPagoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HoraPagoField, value) <> true) Then
                    Me.HoraPagoField = value
                    Me.RaisePropertyChanged("HoraPago")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCliente() As Integer
            Get
                Return Me.IdClienteField
            End Get
            Set
                If (Me.IdClienteField.Equals(value) <> true) Then
                    Me.IdClienteField = value
                    Me.RaisePropertyChanged("IdCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LimiteCredito() As Double
            Get
                Return Me.LimiteCreditoField
            End Get
            Set
                If (Me.LimiteCreditoField.Equals(value) <> true) Then
                    Me.LimiteCreditoField = value
                    Me.RaisePropertyChanged("LimiteCredito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ListaCli() As Boolean
            Get
                Return Me.ListaCliField
            End Get
            Set
                If (Me.ListaCliField.Equals(value) <> true) Then
                    Me.ListaCliField = value
                    Me.RaisePropertyChanged("ListaCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Moneda() As ListaClienteCabService.Moneda
            Get
                Return Me.MonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonedaField, value) <> true) Then
                    Me.MonedaField = value
                    Me.RaisePropertyChanged("Moneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumCta() As String
            Get
                Return Me.NumCtaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumCtaField, value) <> true) Then
                    Me.NumCtaField = value
                    Me.RaisePropertyChanged("NumCta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ObsCli() As String
            Get
                Return Me.ObsCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObsCliField, value) <> true) Then
                    Me.ObsCliField = value
                    Me.RaisePropertyChanged("ObsCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucCli() As String
            Get
                Return Me.RucCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucCliField, value) <> true) Then
                    Me.RucCliField = value
                    Me.RaisePropertyChanged("RucCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SectorCliente() As ListaClienteCabService.SectorCliente
            Get
                Return Me.SectorClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SectorClienteField, value) <> true) Then
                    Me.SectorClienteField = value
                    Me.RaisePropertyChanged("SectorCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelCli() As String
            Get
                Return Me.TelCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelCliField, value) <> true) Then
                    Me.TelCliField = value
                    Me.RaisePropertyChanged("TelCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoCliente() As ListaClienteCabService.TipoCliente
            Get
                Return Me.TipoClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoClienteField, value) <> true) Then
                    Me.TipoClienteField = value
                    Me.RaisePropertyChanged("TipoCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoContribuyente() As ListaClienteCabService.TipoContribuyente
            Get
                Return Me.TipoContribuyenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoContribuyenteField, value) <> true) Then
                    Me.TipoContribuyenteField = value
                    Me.RaisePropertyChanged("TipoContribuyente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumentoId() As ListaClienteCabService.TipoDocumentoId
            Get
                Return Me.TipoDocumentoIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoIdField, value) <> true) Then
                    Me.TipoDocumentoIdField = value
                    Me.RaisePropertyChanged("TipoDocumentoId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoMedioContacto() As ListaClienteCabService.TipoMedioContacto
            Get
                Return Me.TipoMedioContactoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoMedioContactoField, value) <> true) Then
                    Me.TipoMedioContactoField = value
                    Me.RaisePropertyChanged("TipoMedioContacto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UrlCli() As String
            Get
                Return Me.UrlCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UrlCliField, value) <> true) Then
                    Me.UrlCliField = value
                    Me.RaisePropertyChanged("UrlCli")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoListaPrecioCliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoListaPrecioCliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdEstadoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEstado() As String
            Get
                Return Me.AbrEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEstadoField, value) <> true) Then
                    Me.AbrEstadoField = value
                    Me.RaisePropertyChanged("AbrEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEstado() As String
            Get
                Return Me.DesEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEstadoField, value) <> true) Then
                    Me.DesEstadoField = value
                    Me.RaisePropertyChanged("DesEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdEstado() As Integer
            Get
                Return Me.IdEstadoField
            End Get
            Set
                If (Me.IdEstadoField.Equals(value) <> true) Then
                    Me.IdEstadoField = value
                    Me.RaisePropertyChanged("IdEstado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Moneda", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Moneda
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesMonField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrMon() As String
            Get
                Return Me.AbrMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrMonField, value) <> true) Then
                    Me.AbrMonField = value
                    Me.RaisePropertyChanged("AbrMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodMon() As String
            Get
                Return Me.CodMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodMonField, value) <> true) Then
                    Me.CodMonField = value
                    Me.RaisePropertyChanged("CodMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesMon() As String
            Get
                Return Me.DesMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesMonField, value) <> true) Then
                    Me.DesMonField = value
                    Me.RaisePropertyChanged("DesMon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SectorCliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SectorCliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrSecField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodSecField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesSecField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrSec() As String
            Get
                Return Me.AbrSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrSecField, value) <> true) Then
                    Me.AbrSecField = value
                    Me.RaisePropertyChanged("AbrSec")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodSec() As String
            Get
                Return Me.CodSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodSecField, value) <> true) Then
                    Me.CodSecField = value
                    Me.RaisePropertyChanged("CodSec")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesSec() As String
            Get
                Return Me.DesSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesSecField, value) <> true) Then
                    Me.DesSecField = value
                    Me.RaisePropertyChanged("DesSec")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoCliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoCliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesTipoCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTipoClienteField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrTipo() As String
            Get
                Return Me.AbrTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrTipoField, value) <> true) Then
                    Me.AbrTipoField = value
                    Me.RaisePropertyChanged("AbrTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesTipoCli() As String
            Get
                Return Me.DesTipoCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesTipoCliField, value) <> true) Then
                    Me.DesTipoCliField = value
                    Me.RaisePropertyChanged("DesTipoCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTipoCliente() As Integer
            Get
                Return Me.IdTipoClienteField
            End Get
            Set
                If (Me.IdTipoClienteField.Equals(value) <> true) Then
                    Me.IdTipoClienteField = value
                    Me.RaisePropertyChanged("IdTipoCliente")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoContribuyente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoContribuyente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTipoConField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrTipo() As String
            Get
                Return Me.AbrTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrTipoField, value) <> true) Then
                    Me.AbrTipoField = value
                    Me.RaisePropertyChanged("AbrTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesTipo() As String
            Get
                Return Me.DesTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesTipoField, value) <> true) Then
                    Me.DesTipoField = value
                    Me.RaisePropertyChanged("DesTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTipoCon() As Integer
            Get
                Return Me.IdTipoConField
            End Get
            Set
                If (Me.IdTipoConField.Equals(value) <> true) Then
                    Me.IdTipoConField = value
                    Me.RaisePropertyChanged("IdTipoCon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoDocumentoId", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoDocumentoId
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrDocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesDocField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrDoc() As String
            Get
                Return Me.AbrDocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrDocField, value) <> true) Then
                    Me.AbrDocField = value
                    Me.RaisePropertyChanged("AbrDoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDoc() As String
            Get
                Return Me.CodDocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDocField, value) <> true) Then
                    Me.CodDocField = value
                    Me.RaisePropertyChanged("CodDoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesDoc() As String
            Get
                Return Me.DesDocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesDocField, value) <> true) Then
                    Me.DesDocField = value
                    Me.RaisePropertyChanged("DesDoc")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoMedioContacto", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoMedioContacto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrMedioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesMedioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMedioField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrMedio() As String
            Get
                Return Me.AbrMedioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrMedioField, value) <> true) Then
                    Me.AbrMedioField = value
                    Me.RaisePropertyChanged("AbrMedio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesMedio() As String
            Get
                Return Me.DesMedioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesMedioField, value) <> true) Then
                    Me.DesMedioField = value
                    Me.RaisePropertyChanged("DesMedio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMedio() As System.Nullable(Of Integer)
            Get
                Return Me.IdMedioField
            End Get
            Set
                If (Me.IdMedioField.Equals(value) <> true) Then
                    Me.IdMedioField = value
                    Me.RaisePropertyChanged("IdMedio")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ListaClienteCabService.IListaClienteCabService")>  _
    Public Interface IListaClienteCabService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Insertar", ReplyAction:="http://tempuri.org/IListaClienteCabService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Registro As ListaClienteCabService.ListaClienteCab) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Actualizar", ReplyAction:="http://tempuri.org/IListaClienteCabService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Registro As ListaClienteCabService.ListaClienteCab) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Borrar", ReplyAction:="http://tempuri.org/IListaClienteCabService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pIdLista As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Filtrar", ReplyAction:="http://tempuri.org/IListaClienteCabService/FiltrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Filtrar(ByVal pCodEmp As String, ByVal pIdCliente As Long, ByVal pNumContrato As String, ByVal pIdEstado As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Obtener", ReplyAction:="http://tempuri.org/IListaClienteCabService/ObtenerResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Obtener(ByVal pIdLista As Integer) As ListaClienteCabService.ListaClienteCab
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/AprobacionJefe", ReplyAction:="http://tempuri.org/IListaClienteCabService/AprobacionJefeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function AprobacionJefe(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/AprobacionGerencia", ReplyAction:="http://tempuri.org/IListaClienteCabService/AprobacionGerenciaResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function AprobacionGerencia(ByVal pIdLista As Long, ByVal Detalle As System.Data.DataTable, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Rechazar", ReplyAction:="http://tempuri.org/IListaClienteCabService/RechazarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Rechazar(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Enviar", ReplyAction:="http://tempuri.org/IListaClienteCabService/EnviarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Enviar(ByVal pIdLista As Integer, ByVal Correos As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/Imprimir", ReplyAction:="http://tempuri.org/IListaClienteCabService/ImprimirResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Imprimir(ByVal pIdLista As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/ObtenerEstado", ReplyAction:="http://tempuri.org/IListaClienteCabService/ObtenerEstadoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ObtenerEstado(ByVal pIdLista As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/ConsultarEstados", ReplyAction:="http://tempuri.org/IListaClienteCabService/ConsultarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ConsultarEstados(ByVal pIdLista As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/MostrarEstados", ReplyAction:="http://tempuri.org/IListaClienteCabService/MostrarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarEstados() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/VencimientoLista", ReplyAction:="http://tempuri.org/IListaClienteCabService/VencimientoListaResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function VencimientoLista(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/MostrarPendientes", ReplyAction:="http://tempuri.org/IListaClienteCabService/MostrarPendientesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarPendientes(ByVal pIdLista As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/BuscarAprobacionPendiente", ReplyAction:="http://tempuri.org/IListaClienteCabService/BuscarAprobacionPendienteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function BuscarAprobacionPendiente(ByVal pIdLista As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaClienteCabService/ActualizarFechaVencimiento", ReplyAction:="http://tempuri.org/IListaClienteCabService/ActualizarFechaVencimientoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaClienteCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ActualizarFechaVencimiento(ByVal pIdLista As Long, ByVal pFecVencimiento As Date, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IListaClienteCabServiceChannel
        Inherits ListaClienteCabService.IListaClienteCabService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ListaClienteCabServiceClient
        Inherits System.ServiceModel.ClientBase(Of ListaClienteCabService.IListaClienteCabService)
        Implements ListaClienteCabService.IListaClienteCabService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Insertar(ByVal Registro As ListaClienteCabService.ListaClienteCab) As Integer Implements ListaClienteCabService.IListaClienteCabService.Insertar
            Return MyBase.Channel.Insertar(Registro)
        End Function
        
        Public Function Actualizar(ByVal Registro As ListaClienteCabService.ListaClienteCab) As Boolean Implements ListaClienteCabService.IListaClienteCabService.Actualizar
            Return MyBase.Channel.Actualizar(Registro)
        End Function
        
        Public Function Borrar(ByVal pIdLista As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.Borrar
            Return MyBase.Channel.Borrar(pIdLista, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Filtrar(ByVal pCodEmp As String, ByVal pIdCliente As Long, ByVal pNumContrato As String, ByVal pIdEstado As Integer) As System.Data.DataSet Implements ListaClienteCabService.IListaClienteCabService.Filtrar
            Return MyBase.Channel.Filtrar(pCodEmp, pIdCliente, pNumContrato, pIdEstado)
        End Function
        
        Public Function Obtener(ByVal pIdLista As Integer) As ListaClienteCabService.ListaClienteCab Implements ListaClienteCabService.IListaClienteCabService.Obtener
            Return MyBase.Channel.Obtener(pIdLista)
        End Function
        
        Public Function AprobacionJefe(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.AprobacionJefe
            Return MyBase.Channel.AprobacionJefe(pIdLista, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function AprobacionGerencia(ByVal pIdLista As Long, ByVal Detalle As System.Data.DataTable, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.AprobacionGerencia
            Return MyBase.Channel.AprobacionGerencia(pIdLista, Detalle, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Rechazar(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.Rechazar
            Return MyBase.Channel.Rechazar(pIdLista, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Enviar(ByVal pIdLista As Integer, ByVal Correos As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.Enviar
            Return MyBase.Channel.Enviar(pIdLista, Correos, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Imprimir(ByVal pIdLista As Integer) As System.Data.DataSet Implements ListaClienteCabService.IListaClienteCabService.Imprimir
            Return MyBase.Channel.Imprimir(pIdLista)
        End Function
        
        Public Function ObtenerEstado(ByVal pIdLista As Integer) As Integer Implements ListaClienteCabService.IListaClienteCabService.ObtenerEstado
            Return MyBase.Channel.ObtenerEstado(pIdLista)
        End Function
        
        Public Function ConsultarEstados(ByVal pIdLista As Integer) As System.Data.DataSet Implements ListaClienteCabService.IListaClienteCabService.ConsultarEstados
            Return MyBase.Channel.ConsultarEstados(pIdLista)
        End Function
        
        Public Function MostrarEstados() As System.Data.DataSet Implements ListaClienteCabService.IListaClienteCabService.MostrarEstados
            Return MyBase.Channel.MostrarEstados
        End Function
        
        Public Function VencimientoLista(ByVal pIdLista As Integer, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.VencimientoLista
            Return MyBase.Channel.VencimientoLista(pIdLista, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function MostrarPendientes(ByVal pIdLista As Long) As System.Data.DataSet Implements ListaClienteCabService.IListaClienteCabService.MostrarPendientes
            Return MyBase.Channel.MostrarPendientes(pIdLista)
        End Function
        
        Public Function BuscarAprobacionPendiente(ByVal pIdLista As Long) As Boolean Implements ListaClienteCabService.IListaClienteCabService.BuscarAprobacionPendiente
            Return MyBase.Channel.BuscarAprobacionPendiente(pIdLista)
        End Function
        
        Public Function ActualizarFechaVencimiento(ByVal pIdLista As Long, ByVal pFecVencimiento As Date, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaClienteCabService.IListaClienteCabService.ActualizarFechaVencimiento
            Return MyBase.Channel.ActualizarFechaVencimiento(pIdLista, pFecVencimiento, pCodUsu, pNomPc, pDirIp)
        End Function
    End Class
End Namespace
