<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>sigecoom_wcf_adapter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="10.0.652802" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sigecoom-wcf-proxies\sigecoom-wcf-proxies.vbproj" />
  </ItemGroup>

</Project>
