'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ClienteFacDscService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClienteFacDsc", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClienteFacDsc
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClienteField As ClienteFacDscService.Cliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DNCliField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DscCliField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As ClienteFacDscService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FacCliField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RubroField As ClienteFacDscService.Rubro
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cliente() As ClienteFacDscService.Cliente
            Get
                Return Me.ClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClienteField, value) <> true) Then
                    Me.ClienteField = value
                    Me.RaisePropertyChanged("Cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DNCli() As Boolean
            Get
                Return Me.DNCliField
            End Get
            Set
                If (Me.DNCliField.Equals(value) <> true) Then
                    Me.DNCliField = value
                    Me.RaisePropertyChanged("DNCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DscCli() As Double
            Get
                Return Me.DscCliField
            End Get
            Set
                If (Me.DscCliField.Equals(value) <> true) Then
                    Me.DscCliField = value
                    Me.RaisePropertyChanged("DscCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As ClienteFacDscService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FacCli() As Double
            Get
                Return Me.FacCliField
            End Get
            Set
                If (Me.FacCliField.Equals(value) <> true) Then
                    Me.FacCliField = value
                    Me.RaisePropertyChanged("FacCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rubro() As ClienteFacDscService.Rubro
            Get
                Return Me.RubroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RubroField, value) <> true) Then
                    Me.RubroField = value
                    Me.RaisePropertyChanged("Rubro")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApeMatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApePatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AprCliField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiaPagoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DniCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DueCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecIngField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraPagoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LimiteCreditoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ListaCliField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonedaField As ClienteFacDscService.Moneda
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumCtaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObsCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SectorClienteField As ClienteFacDscService.SectorCliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoClienteField As ClienteFacDscService.TipoCliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoContribuyenteField As ClienteFacDscService.TipoContribuyente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UrlCliField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrCli() As String
            Get
                Return Me.AbrCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrCliField, value) <> true) Then
                    Me.AbrCliField = value
                    Me.RaisePropertyChanged("AbrCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApeMat() As String
            Get
                Return Me.ApeMatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApeMatField, value) <> true) Then
                    Me.ApeMatField = value
                    Me.RaisePropertyChanged("ApeMat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApePat() As String
            Get
                Return Me.ApePatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApePatField, value) <> true) Then
                    Me.ApePatField = value
                    Me.RaisePropertyChanged("ApePat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AprCli() As Boolean
            Get
                Return Me.AprCliField
            End Get
            Set
                If (Me.AprCliField.Equals(value) <> true) Then
                    Me.AprCliField = value
                    Me.RaisePropertyChanged("AprCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesCli() As String
            Get
                Return Me.DesCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesCliField, value) <> true) Then
                    Me.DesCliField = value
                    Me.RaisePropertyChanged("DesCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DiaPago() As String
            Get
                Return Me.DiaPagoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DiaPagoField, value) <> true) Then
                    Me.DiaPagoField = value
                    Me.RaisePropertyChanged("DiaPago")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DniCli() As String
            Get
                Return Me.DniCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DniCliField, value) <> true) Then
                    Me.DniCliField = value
                    Me.RaisePropertyChanged("DniCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DueCli() As String
            Get
                Return Me.DueCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DueCliField, value) <> true) Then
                    Me.DueCliField = value
                    Me.RaisePropertyChanged("DueCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As Integer
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Me.EstadoField.Equals(value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxCli() As String
            Get
                Return Me.FaxCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxCliField, value) <> true) Then
                    Me.FaxCliField = value
                    Me.RaisePropertyChanged("FaxCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecIng() As Date
            Get
                Return Me.FecIngField
            End Get
            Set
                If (Me.FecIngField.Equals(value) <> true) Then
                    Me.FecIngField = value
                    Me.RaisePropertyChanged("FecIng")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraPago() As String
            Get
                Return Me.HoraPagoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HoraPagoField, value) <> true) Then
                    Me.HoraPagoField = value
                    Me.RaisePropertyChanged("HoraPago")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCliente() As Integer
            Get
                Return Me.IdClienteField
            End Get
            Set
                If (Me.IdClienteField.Equals(value) <> true) Then
                    Me.IdClienteField = value
                    Me.RaisePropertyChanged("IdCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LimiteCredito() As Double
            Get
                Return Me.LimiteCreditoField
            End Get
            Set
                If (Me.LimiteCreditoField.Equals(value) <> true) Then
                    Me.LimiteCreditoField = value
                    Me.RaisePropertyChanged("LimiteCredito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ListaCli() As Boolean
            Get
                Return Me.ListaCliField
            End Get
            Set
                If (Me.ListaCliField.Equals(value) <> true) Then
                    Me.ListaCliField = value
                    Me.RaisePropertyChanged("ListaCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Moneda() As ClienteFacDscService.Moneda
            Get
                Return Me.MonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonedaField, value) <> true) Then
                    Me.MonedaField = value
                    Me.RaisePropertyChanged("Moneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumCta() As String
            Get
                Return Me.NumCtaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumCtaField, value) <> true) Then
                    Me.NumCtaField = value
                    Me.RaisePropertyChanged("NumCta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ObsCli() As String
            Get
                Return Me.ObsCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObsCliField, value) <> true) Then
                    Me.ObsCliField = value
                    Me.RaisePropertyChanged("ObsCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucCli() As String
            Get
                Return Me.RucCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucCliField, value) <> true) Then
                    Me.RucCliField = value
                    Me.RaisePropertyChanged("RucCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SectorCliente() As ClienteFacDscService.SectorCliente
            Get
                Return Me.SectorClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SectorClienteField, value) <> true) Then
                    Me.SectorClienteField = value
                    Me.RaisePropertyChanged("SectorCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelCli() As String
            Get
                Return Me.TelCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelCliField, value) <> true) Then
                    Me.TelCliField = value
                    Me.RaisePropertyChanged("TelCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoCliente() As ClienteFacDscService.TipoCliente
            Get
                Return Me.TipoClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoClienteField, value) <> true) Then
                    Me.TipoClienteField = value
                    Me.RaisePropertyChanged("TipoCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoContribuyente() As ClienteFacDscService.TipoContribuyente
            Get
                Return Me.TipoContribuyenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoContribuyenteField, value) <> true) Then
                    Me.TipoContribuyenteField = value
                    Me.RaisePropertyChanged("TipoContribuyente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UrlCli() As String
            Get
                Return Me.UrlCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UrlCliField, value) <> true) Then
                    Me.UrlCliField = value
                    Me.RaisePropertyChanged("UrlCli")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Rubro", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Rubro
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrRubField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodRubField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesRubField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DsctoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FacCosField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FacVenField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrRub() As String
            Get
                Return Me.AbrRubField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrRubField, value) <> true) Then
                    Me.AbrRubField = value
                    Me.RaisePropertyChanged("AbrRub")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodRub() As String
            Get
                Return Me.CodRubField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodRubField, value) <> true) Then
                    Me.CodRubField = value
                    Me.RaisePropertyChanged("CodRub")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesRub() As String
            Get
                Return Me.DesRubField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesRubField, value) <> true) Then
                    Me.DesRubField = value
                    Me.RaisePropertyChanged("DesRub")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Dscto() As Double
            Get
                Return Me.DsctoField
            End Get
            Set
                If (Me.DsctoField.Equals(value) <> true) Then
                    Me.DsctoField = value
                    Me.RaisePropertyChanged("Dscto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FacCos() As Double
            Get
                Return Me.FacCosField
            End Get
            Set
                If (Me.FacCosField.Equals(value) <> true) Then
                    Me.FacCosField = value
                    Me.RaisePropertyChanged("FacCos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FacVen() As Double
            Get
                Return Me.FacVenField
            End Get
            Set
                If (Me.FacVenField.Equals(value) <> true) Then
                    Me.FacVenField = value
                    Me.RaisePropertyChanged("FacVen")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Moneda", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Moneda
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesMonField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrMon() As String
            Get
                Return Me.AbrMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrMonField, value) <> true) Then
                    Me.AbrMonField = value
                    Me.RaisePropertyChanged("AbrMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodMon() As String
            Get
                Return Me.CodMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodMonField, value) <> true) Then
                    Me.CodMonField = value
                    Me.RaisePropertyChanged("CodMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesMon() As String
            Get
                Return Me.DesMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesMonField, value) <> true) Then
                    Me.DesMonField = value
                    Me.RaisePropertyChanged("DesMon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SectorCliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SectorCliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrSecField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodSecField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesSecField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrSec() As String
            Get
                Return Me.AbrSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrSecField, value) <> true) Then
                    Me.AbrSecField = value
                    Me.RaisePropertyChanged("AbrSec")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodSec() As String
            Get
                Return Me.CodSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodSecField, value) <> true) Then
                    Me.CodSecField = value
                    Me.RaisePropertyChanged("CodSec")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesSec() As String
            Get
                Return Me.DesSecField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesSecField, value) <> true) Then
                    Me.DesSecField = value
                    Me.RaisePropertyChanged("DesSec")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoCliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoCliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesTipoCliField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTipoClienteField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrTipo() As String
            Get
                Return Me.AbrTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrTipoField, value) <> true) Then
                    Me.AbrTipoField = value
                    Me.RaisePropertyChanged("AbrTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesTipoCli() As String
            Get
                Return Me.DesTipoCliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesTipoCliField, value) <> true) Then
                    Me.DesTipoCliField = value
                    Me.RaisePropertyChanged("DesTipoCli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTipoCliente() As Integer
            Get
                Return Me.IdTipoClienteField
            End Get
            Set
                If (Me.IdTipoClienteField.Equals(value) <> true) Then
                    Me.IdTipoClienteField = value
                    Me.RaisePropertyChanged("IdTipoCliente")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoContribuyente", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoContribuyente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesTipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTipoConField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrTipo() As String
            Get
                Return Me.AbrTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrTipoField, value) <> true) Then
                    Me.AbrTipoField = value
                    Me.RaisePropertyChanged("AbrTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesTipo() As String
            Get
                Return Me.DesTipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesTipoField, value) <> true) Then
                    Me.DesTipoField = value
                    Me.RaisePropertyChanged("DesTipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTipoCon() As Integer
            Get
                Return Me.IdTipoConField
            End Get
            Set
                If (Me.IdTipoConField.Equals(value) <> true) Then
                    Me.IdTipoConField = value
                    Me.RaisePropertyChanged("IdTipoCon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ClienteFacDscService.IClienteFacDscService")>  _
    Public Interface IClienteFacDscService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/MostrarPorId", ReplyAction:="http://tempuri.org/IClienteFacDscService/MostrarPorIdResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarPorId(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer) As ClienteFacDscService.ClienteFacDsc
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/MostrarPorId", ReplyAction:="http://tempuri.org/IClienteFacDscService/MostrarPorIdResponse")>  _
        Function BeginMostrarPorId(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndMostrarPorId(ByVal result As System.IAsyncResult) As ClienteFacDscService.ClienteFacDsc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Filtrar", ReplyAction:="http://tempuri.org/IClienteFacDscService/FiltrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Filtrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Filtrar", ReplyAction:="http://tempuri.org/IClienteFacDscService/FiltrarResponse")>  _
        Function BeginFiltrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndFiltrar(ByVal result As System.IAsyncResult) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Buscar", ReplyAction:="http://tempuri.org/IClienteFacDscService/BuscarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Buscar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Buscar", ReplyAction:="http://tempuri.org/IClienteFacDscService/BuscarResponse")>  _
        Function BeginBuscar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndBuscar(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Insertar", ReplyAction:="http://tempuri.org/IClienteFacDscService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Clase As ClienteFacDscService.ClienteFacDsc) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Insertar", ReplyAction:="http://tempuri.org/IClienteFacDscService/InsertarResponse")>  _
        Function BeginInsertar(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndInsertar(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Actualizar", ReplyAction:="http://tempuri.org/IClienteFacDscService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Clase As ClienteFacDscService.ClienteFacDsc) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Actualizar", ReplyAction:="http://tempuri.org/IClienteFacDscService/ActualizarResponse")>  _
        Function BeginActualizar(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndActualizar(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Borrar", ReplyAction:="http://tempuri.org/IClienteFacDscService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Borrar", ReplyAction:="http://tempuri.org/IClienteFacDscService/BorrarResponse")>  _
        Function BeginBorrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndBorrar(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteFacDscService/Imprimir", ReplyAction:="http://tempuri.org/IClienteFacDscService/ImprimirResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ClienteFacDscService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Imprimir(ByVal pCodEmp As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IClienteFacDscService/Imprimir", ReplyAction:="http://tempuri.org/IClienteFacDscService/ImprimirResponse")>  _
        Function BeginImprimir(ByVal pCodEmp As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndImprimir(ByVal result As System.IAsyncResult) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IClienteFacDscServiceChannel
        Inherits ClienteFacDscService.IClienteFacDscService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MostrarPorIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As ClienteFacDscService.ClienteFacDsc
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClienteFacDscService.ClienteFacDsc)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FiltrarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BuscarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InsertarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ActualizarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BorrarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImprimirCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClienteFacDscServiceClient
        Inherits System.ServiceModel.ClientBase(Of ClienteFacDscService.IClienteFacDscService)
        Implements ClienteFacDscService.IClienteFacDscService
        
        Private onBeginMostrarPorIdDelegate As BeginOperationDelegate
        
        Private onEndMostrarPorIdDelegate As EndOperationDelegate
        
        Private onMostrarPorIdCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginFiltrarDelegate As BeginOperationDelegate
        
        Private onEndFiltrarDelegate As EndOperationDelegate
        
        Private onFiltrarCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginBuscarDelegate As BeginOperationDelegate
        
        Private onEndBuscarDelegate As EndOperationDelegate
        
        Private onBuscarCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginInsertarDelegate As BeginOperationDelegate
        
        Private onEndInsertarDelegate As EndOperationDelegate
        
        Private onInsertarCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginActualizarDelegate As BeginOperationDelegate
        
        Private onEndActualizarDelegate As EndOperationDelegate
        
        Private onActualizarCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginBorrarDelegate As BeginOperationDelegate
        
        Private onEndBorrarDelegate As EndOperationDelegate
        
        Private onBorrarCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginImprimirDelegate As BeginOperationDelegate
        
        Private onEndImprimirDelegate As EndOperationDelegate
        
        Private onImprimirCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event MostrarPorIdCompleted As System.EventHandler(Of MostrarPorIdCompletedEventArgs)
        
        Public Event FiltrarCompleted As System.EventHandler(Of FiltrarCompletedEventArgs)
        
        Public Event BuscarCompleted As System.EventHandler(Of BuscarCompletedEventArgs)
        
        Public Event InsertarCompleted As System.EventHandler(Of InsertarCompletedEventArgs)
        
        Public Event ActualizarCompleted As System.EventHandler(Of ActualizarCompletedEventArgs)
        
        Public Event BorrarCompleted As System.EventHandler(Of BorrarCompletedEventArgs)
        
        Public Event ImprimirCompleted As System.EventHandler(Of ImprimirCompletedEventArgs)
        
        Public Function MostrarPorId(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer) As ClienteFacDscService.ClienteFacDsc Implements ClienteFacDscService.IClienteFacDscService.MostrarPorId
            Return MyBase.Channel.MostrarPorId(pCodEmp, pCodRub, pIdCliente)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginMostrarPorId(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginMostrarPorId
            Return MyBase.Channel.BeginMostrarPorId(pCodEmp, pCodRub, pIdCliente, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndMostrarPorId(ByVal result As System.IAsyncResult) As ClienteFacDscService.ClienteFacDsc Implements ClienteFacDscService.IClienteFacDscService.EndMostrarPorId
            Return MyBase.Channel.EndMostrarPorId(result)
        End Function
        
        Private Function OnBeginMostrarPorId(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pCodEmp As String = CType(inValues(0),String)
            Dim pCodRub As String = CType(inValues(1),String)
            Dim pIdCliente As Integer = CType(inValues(2),Integer)
            Return Me.BeginMostrarPorId(pCodEmp, pCodRub, pIdCliente, callback, asyncState)
        End Function
        
        Private Function OnEndMostrarPorId(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As ClienteFacDscService.ClienteFacDsc = Me.EndMostrarPorId(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnMostrarPorIdCompleted(ByVal state As Object)
            If (Not (Me.MostrarPorIdCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent MostrarPorIdCompleted(Me, New MostrarPorIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub MostrarPorIdAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer)
            Me.MostrarPorIdAsync(pCodEmp, pCodRub, pIdCliente, Nothing)
        End Sub
        
        Public Overloads Sub MostrarPorIdAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal userState As Object)
            If (Me.onBeginMostrarPorIdDelegate Is Nothing) Then
                Me.onBeginMostrarPorIdDelegate = AddressOf Me.OnBeginMostrarPorId
            End If
            If (Me.onEndMostrarPorIdDelegate Is Nothing) Then
                Me.onEndMostrarPorIdDelegate = AddressOf Me.OnEndMostrarPorId
            End If
            If (Me.onMostrarPorIdCompletedDelegate Is Nothing) Then
                Me.onMostrarPorIdCompletedDelegate = AddressOf Me.OnMostrarPorIdCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginMostrarPorIdDelegate, New Object() {pCodEmp, pCodRub, pIdCliente}, Me.onEndMostrarPorIdDelegate, Me.onMostrarPorIdCompletedDelegate, userState)
        End Sub
        
        Public Function Filtrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double) As System.Data.DataSet Implements ClienteFacDscService.IClienteFacDscService.Filtrar
            Return MyBase.Channel.Filtrar(pCodEmp, pCodRub, pIdCliente, pFacCli, pDscCli)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginFiltrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginFiltrar
            Return MyBase.Channel.BeginFiltrar(pCodEmp, pCodRub, pIdCliente, pFacCli, pDscCli, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndFiltrar(ByVal result As System.IAsyncResult) As System.Data.DataSet Implements ClienteFacDscService.IClienteFacDscService.EndFiltrar
            Return MyBase.Channel.EndFiltrar(result)
        End Function
        
        Private Function OnBeginFiltrar(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pCodEmp As String = CType(inValues(0),String)
            Dim pCodRub As String = CType(inValues(1),String)
            Dim pIdCliente As Integer = CType(inValues(2),Integer)
            Dim pFacCli As Double = CType(inValues(3),Double)
            Dim pDscCli As Double = CType(inValues(4),Double)
            Return Me.BeginFiltrar(pCodEmp, pCodRub, pIdCliente, pFacCli, pDscCli, callback, asyncState)
        End Function
        
        Private Function OnEndFiltrar(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Data.DataSet = Me.EndFiltrar(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnFiltrarCompleted(ByVal state As Object)
            If (Not (Me.FiltrarCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent FiltrarCompleted(Me, New FiltrarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub FiltrarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double)
            Me.FiltrarAsync(pCodEmp, pCodRub, pIdCliente, pFacCli, pDscCli, Nothing)
        End Sub
        
        Public Overloads Sub FiltrarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal pFacCli As Double, ByVal pDscCli As Double, ByVal userState As Object)
            If (Me.onBeginFiltrarDelegate Is Nothing) Then
                Me.onBeginFiltrarDelegate = AddressOf Me.OnBeginFiltrar
            End If
            If (Me.onEndFiltrarDelegate Is Nothing) Then
                Me.onEndFiltrarDelegate = AddressOf Me.OnEndFiltrar
            End If
            If (Me.onFiltrarCompletedDelegate Is Nothing) Then
                Me.onFiltrarCompletedDelegate = AddressOf Me.OnFiltrarCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginFiltrarDelegate, New Object() {pCodEmp, pCodRub, pIdCliente, pFacCli, pDscCli}, Me.onEndFiltrarDelegate, Me.onFiltrarCompletedDelegate, userState)
        End Sub
        
        Public Function Buscar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer) As Boolean Implements ClienteFacDscService.IClienteFacDscService.Buscar
            Return MyBase.Channel.Buscar(pCodEmp, pCodRub, pIdCliente)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginBuscar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginBuscar
            Return MyBase.Channel.BeginBuscar(pCodEmp, pCodRub, pIdCliente, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndBuscar(ByVal result As System.IAsyncResult) As Boolean Implements ClienteFacDscService.IClienteFacDscService.EndBuscar
            Return MyBase.Channel.EndBuscar(result)
        End Function
        
        Private Function OnBeginBuscar(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pCodEmp As String = CType(inValues(0),String)
            Dim pCodRub As String = CType(inValues(1),String)
            Dim pIdCliente As Integer = CType(inValues(2),Integer)
            Return Me.BeginBuscar(pCodEmp, pCodRub, pIdCliente, callback, asyncState)
        End Function
        
        Private Function OnEndBuscar(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndBuscar(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnBuscarCompleted(ByVal state As Object)
            If (Not (Me.BuscarCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent BuscarCompleted(Me, New BuscarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub BuscarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer)
            Me.BuscarAsync(pCodEmp, pCodRub, pIdCliente, Nothing)
        End Sub
        
        Public Overloads Sub BuscarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Integer, ByVal userState As Object)
            If (Me.onBeginBuscarDelegate Is Nothing) Then
                Me.onBeginBuscarDelegate = AddressOf Me.OnBeginBuscar
            End If
            If (Me.onEndBuscarDelegate Is Nothing) Then
                Me.onEndBuscarDelegate = AddressOf Me.OnEndBuscar
            End If
            If (Me.onBuscarCompletedDelegate Is Nothing) Then
                Me.onBuscarCompletedDelegate = AddressOf Me.OnBuscarCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginBuscarDelegate, New Object() {pCodEmp, pCodRub, pIdCliente}, Me.onEndBuscarDelegate, Me.onBuscarCompletedDelegate, userState)
        End Sub
        
        Public Function Insertar(ByVal Clase As ClienteFacDscService.ClienteFacDsc) As Boolean Implements ClienteFacDscService.IClienteFacDscService.Insertar
            Return MyBase.Channel.Insertar(Clase)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginInsertar(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginInsertar
            Return MyBase.Channel.BeginInsertar(Clase, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndInsertar(ByVal result As System.IAsyncResult) As Boolean Implements ClienteFacDscService.IClienteFacDscService.EndInsertar
            Return MyBase.Channel.EndInsertar(result)
        End Function
        
        Private Function OnBeginInsertar(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Clase As ClienteFacDscService.ClienteFacDsc = CType(inValues(0),ClienteFacDscService.ClienteFacDsc)
            Return Me.BeginInsertar(Clase, callback, asyncState)
        End Function
        
        Private Function OnEndInsertar(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndInsertar(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnInsertarCompleted(ByVal state As Object)
            If (Not (Me.InsertarCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent InsertarCompleted(Me, New InsertarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub InsertarAsync(ByVal Clase As ClienteFacDscService.ClienteFacDsc)
            Me.InsertarAsync(Clase, Nothing)
        End Sub
        
        Public Overloads Sub InsertarAsync(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal userState As Object)
            If (Me.onBeginInsertarDelegate Is Nothing) Then
                Me.onBeginInsertarDelegate = AddressOf Me.OnBeginInsertar
            End If
            If (Me.onEndInsertarDelegate Is Nothing) Then
                Me.onEndInsertarDelegate = AddressOf Me.OnEndInsertar
            End If
            If (Me.onInsertarCompletedDelegate Is Nothing) Then
                Me.onInsertarCompletedDelegate = AddressOf Me.OnInsertarCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginInsertarDelegate, New Object() {Clase}, Me.onEndInsertarDelegate, Me.onInsertarCompletedDelegate, userState)
        End Sub
        
        Public Function Actualizar(ByVal Clase As ClienteFacDscService.ClienteFacDsc) As Boolean Implements ClienteFacDscService.IClienteFacDscService.Actualizar
            Return MyBase.Channel.Actualizar(Clase)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginActualizar(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginActualizar
            Return MyBase.Channel.BeginActualizar(Clase, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndActualizar(ByVal result As System.IAsyncResult) As Boolean Implements ClienteFacDscService.IClienteFacDscService.EndActualizar
            Return MyBase.Channel.EndActualizar(result)
        End Function
        
        Private Function OnBeginActualizar(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Clase As ClienteFacDscService.ClienteFacDsc = CType(inValues(0),ClienteFacDscService.ClienteFacDsc)
            Return Me.BeginActualizar(Clase, callback, asyncState)
        End Function
        
        Private Function OnEndActualizar(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndActualizar(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnActualizarCompleted(ByVal state As Object)
            If (Not (Me.ActualizarCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ActualizarCompleted(Me, New ActualizarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ActualizarAsync(ByVal Clase As ClienteFacDscService.ClienteFacDsc)
            Me.ActualizarAsync(Clase, Nothing)
        End Sub
        
        Public Overloads Sub ActualizarAsync(ByVal Clase As ClienteFacDscService.ClienteFacDsc, ByVal userState As Object)
            If (Me.onBeginActualizarDelegate Is Nothing) Then
                Me.onBeginActualizarDelegate = AddressOf Me.OnBeginActualizar
            End If
            If (Me.onEndActualizarDelegate Is Nothing) Then
                Me.onEndActualizarDelegate = AddressOf Me.OnEndActualizar
            End If
            If (Me.onActualizarCompletedDelegate Is Nothing) Then
                Me.onActualizarCompletedDelegate = AddressOf Me.OnActualizarCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginActualizarDelegate, New Object() {Clase}, Me.onEndActualizarDelegate, Me.onActualizarCompletedDelegate, userState)
        End Sub
        
        Public Function Borrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String) As Boolean Implements ClienteFacDscService.IClienteFacDscService.Borrar
            Return MyBase.Channel.Borrar(pCodEmp, pCodRub, pIdCliente, pCodUsu)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginBorrar(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginBorrar
            Return MyBase.Channel.BeginBorrar(pCodEmp, pCodRub, pIdCliente, pCodUsu, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndBorrar(ByVal result As System.IAsyncResult) As Boolean Implements ClienteFacDscService.IClienteFacDscService.EndBorrar
            Return MyBase.Channel.EndBorrar(result)
        End Function
        
        Private Function OnBeginBorrar(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pCodEmp As String = CType(inValues(0),String)
            Dim pCodRub As String = CType(inValues(1),String)
            Dim pIdCliente As Long = CType(inValues(2),Long)
            Dim pCodUsu As String = CType(inValues(3),String)
            Return Me.BeginBorrar(pCodEmp, pCodRub, pIdCliente, pCodUsu, callback, asyncState)
        End Function
        
        Private Function OnEndBorrar(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndBorrar(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnBorrarCompleted(ByVal state As Object)
            If (Not (Me.BorrarCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent BorrarCompleted(Me, New BorrarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub BorrarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String)
            Me.BorrarAsync(pCodEmp, pCodRub, pIdCliente, pCodUsu, Nothing)
        End Sub
        
        Public Overloads Sub BorrarAsync(ByVal pCodEmp As String, ByVal pCodRub As String, ByVal pIdCliente As Long, ByVal pCodUsu As String, ByVal userState As Object)
            If (Me.onBeginBorrarDelegate Is Nothing) Then
                Me.onBeginBorrarDelegate = AddressOf Me.OnBeginBorrar
            End If
            If (Me.onEndBorrarDelegate Is Nothing) Then
                Me.onEndBorrarDelegate = AddressOf Me.OnEndBorrar
            End If
            If (Me.onBorrarCompletedDelegate Is Nothing) Then
                Me.onBorrarCompletedDelegate = AddressOf Me.OnBorrarCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginBorrarDelegate, New Object() {pCodEmp, pCodRub, pIdCliente, pCodUsu}, Me.onEndBorrarDelegate, Me.onBorrarCompletedDelegate, userState)
        End Sub
        
        Public Function Imprimir(ByVal pCodEmp As String) As System.Data.DataSet Implements ClienteFacDscService.IClienteFacDscService.Imprimir
            Return MyBase.Channel.Imprimir(pCodEmp)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginImprimir(ByVal pCodEmp As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ClienteFacDscService.IClienteFacDscService.BeginImprimir
            Return MyBase.Channel.BeginImprimir(pCodEmp, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndImprimir(ByVal result As System.IAsyncResult) As System.Data.DataSet Implements ClienteFacDscService.IClienteFacDscService.EndImprimir
            Return MyBase.Channel.EndImprimir(result)
        End Function
        
        Private Function OnBeginImprimir(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pCodEmp As String = CType(inValues(0),String)
            Return Me.BeginImprimir(pCodEmp, callback, asyncState)
        End Function
        
        Private Function OnEndImprimir(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Data.DataSet = Me.EndImprimir(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnImprimirCompleted(ByVal state As Object)
            If (Not (Me.ImprimirCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ImprimirCompleted(Me, New ImprimirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ImprimirAsync(ByVal pCodEmp As String)
            Me.ImprimirAsync(pCodEmp, Nothing)
        End Sub
        
        Public Overloads Sub ImprimirAsync(ByVal pCodEmp As String, ByVal userState As Object)
            If (Me.onBeginImprimirDelegate Is Nothing) Then
                Me.onBeginImprimirDelegate = AddressOf Me.OnBeginImprimir
            End If
            If (Me.onEndImprimirDelegate Is Nothing) Then
                Me.onEndImprimirDelegate = AddressOf Me.OnEndImprimir
            End If
            If (Me.onImprimirCompletedDelegate Is Nothing) Then
                Me.onImprimirCompletedDelegate = AddressOf Me.OnImprimirCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginImprimirDelegate, New Object() {pCodEmp}, Me.onEndImprimirDelegate, Me.onImprimirCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
