'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ListaOfertaCabService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ListaOfertaCab", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ListaOfertaCab
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As ListaOfertaCabService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoListaPrecioField As ListaOfertaCabService.EstadoListaPrecio
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecVencimientoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdOfertaField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonedaField As ListaOfertaCabService.Moneda
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As ListaOfertaCabService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoListaPrecio() As ListaOfertaCabService.EstadoListaPrecio
            Get
                Return Me.EstadoListaPrecioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoListaPrecioField, value) <> true) Then
                    Me.EstadoListaPrecioField = value
                    Me.RaisePropertyChanged("EstadoListaPrecio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecVencimiento() As Date
            Get
                Return Me.FecVencimientoField
            End Get
            Set
                If (Me.FecVencimientoField.Equals(value) <> true) Then
                    Me.FecVencimientoField = value
                    Me.RaisePropertyChanged("FecVencimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdOferta() As Long
            Get
                Return Me.IdOfertaField
            End Get
            Set
                If (Me.IdOfertaField.Equals(value) <> true) Then
                    Me.IdOfertaField = value
                    Me.RaisePropertyChanged("IdOferta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Moneda() As ListaOfertaCabService.Moneda
            Get
                Return Me.MonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonedaField, value) <> true) Then
                    Me.MonedaField = value
                    Me.RaisePropertyChanged("Moneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoListaPrecio", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoListaPrecio
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdEstadoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEstado() As String
            Get
                Return Me.AbrEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEstadoField, value) <> true) Then
                    Me.AbrEstadoField = value
                    Me.RaisePropertyChanged("AbrEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEstado() As String
            Get
                Return Me.DesEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEstadoField, value) <> true) Then
                    Me.DesEstadoField = value
                    Me.RaisePropertyChanged("DesEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdEstado() As Integer
            Get
                Return Me.IdEstadoField
            End Get
            Set
                If (Me.IdEstadoField.Equals(value) <> true) Then
                    Me.IdEstadoField = value
                    Me.RaisePropertyChanged("IdEstado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Moneda", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Moneda
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesMonField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrMon() As String
            Get
                Return Me.AbrMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrMonField, value) <> true) Then
                    Me.AbrMonField = value
                    Me.RaisePropertyChanged("AbrMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodMon() As String
            Get
                Return Me.CodMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodMonField, value) <> true) Then
                    Me.CodMonField = value
                    Me.RaisePropertyChanged("CodMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesMon() As String
            Get
                Return Me.DesMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesMonField, value) <> true) Then
                    Me.DesMonField = value
                    Me.RaisePropertyChanged("DesMon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ListaOfertaCabService.IListaOfertaCabService")>  _
    Public Interface IListaOfertaCabService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Obtener", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ObtenerResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Obtener(ByVal pIdOferta As Long) As ListaOfertaCabService.ListaOfertaCab
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Filtrar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/FiltrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Filtrar(ByVal pCodEmp As String, ByVal pIdEstado As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Insertar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Registro As ListaOfertaCabService.ListaOfertaCab) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Actualizar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Registro As ListaOfertaCabService.ListaOfertaCab) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Borrar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pIdOferta As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/AprobacionJefe", ReplyAction:="http://tempuri.org/IListaOfertaCabService/AprobacionJefeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function AprobacionJefe(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/AprobacionGerencia", ReplyAction:="http://tempuri.org/IListaOfertaCabService/AprobacionGerenciaResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function AprobacionGerencia(ByVal pIdOferta As Long, ByVal Detalle As System.Data.DataTable, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Rechazar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/RechazarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Rechazar(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Enviar", ReplyAction:="http://tempuri.org/IListaOfertaCabService/EnviarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Enviar(ByVal pIdOferta As Long, ByVal Correos As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/ObtenerEstado", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ObtenerEstadoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ObtenerEstado(ByVal pIdOferta As Long) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/ConsultarEstados", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ConsultarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ConsultarEstados(ByVal pIdOferta As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/MostrarEstados", ReplyAction:="http://tempuri.org/IListaOfertaCabService/MostrarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarEstados() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/VencimientoPrecio", ReplyAction:="http://tempuri.org/IListaOfertaCabService/VencimientoPrecioResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function VencimientoPrecio(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/MostrarPendientes", ReplyAction:="http://tempuri.org/IListaOfertaCabService/MostrarPendientesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarPendientes(ByVal pIdOferta As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/BuscarAprobacionPendiente", ReplyAction:="http://tempuri.org/IListaOfertaCabService/BuscarAprobacionPendienteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function BuscarAprobacionPendiente(ByVal pIdOferta As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/Imprimir", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ImprimirResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Imprimir(ByVal pIdOferta As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IListaOfertaCabService/ActualizarFechaVencimiento", ReplyAction:="http://tempuri.org/IListaOfertaCabService/ActualizarFechaVencimientoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ListaOfertaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ActualizarFechaVencimiento(ByVal pIdOferta As Long, ByVal pFecVencimiento As Date, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IListaOfertaCabServiceChannel
        Inherits ListaOfertaCabService.IListaOfertaCabService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ListaOfertaCabServiceClient
        Inherits System.ServiceModel.ClientBase(Of ListaOfertaCabService.IListaOfertaCabService)
        Implements ListaOfertaCabService.IListaOfertaCabService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Obtener(ByVal pIdOferta As Long) As ListaOfertaCabService.ListaOfertaCab Implements ListaOfertaCabService.IListaOfertaCabService.Obtener
            Return MyBase.Channel.Obtener(pIdOferta)
        End Function
        
        Public Function Filtrar(ByVal pCodEmp As String, ByVal pIdEstado As Integer) As System.Data.DataSet Implements ListaOfertaCabService.IListaOfertaCabService.Filtrar
            Return MyBase.Channel.Filtrar(pCodEmp, pIdEstado)
        End Function
        
        Public Function Insertar(ByVal Registro As ListaOfertaCabService.ListaOfertaCab) As Long Implements ListaOfertaCabService.IListaOfertaCabService.Insertar
            Return MyBase.Channel.Insertar(Registro)
        End Function
        
        Public Function Actualizar(ByVal Registro As ListaOfertaCabService.ListaOfertaCab) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.Actualizar
            Return MyBase.Channel.Actualizar(Registro)
        End Function
        
        Public Function Borrar(ByVal pIdOferta As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.Borrar
            Return MyBase.Channel.Borrar(pIdOferta, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function AprobacionJefe(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.AprobacionJefe
            Return MyBase.Channel.AprobacionJefe(pIdOferta, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function AprobacionGerencia(ByVal pIdOferta As Long, ByVal Detalle As System.Data.DataTable, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As String Implements ListaOfertaCabService.IListaOfertaCabService.AprobacionGerencia
            Return MyBase.Channel.AprobacionGerencia(pIdOferta, Detalle, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Rechazar(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.Rechazar
            Return MyBase.Channel.Rechazar(pIdOferta, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Enviar(ByVal pIdOferta As Long, ByVal Correos As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.Enviar
            Return MyBase.Channel.Enviar(pIdOferta, Correos, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function ObtenerEstado(ByVal pIdOferta As Long) As Integer Implements ListaOfertaCabService.IListaOfertaCabService.ObtenerEstado
            Return MyBase.Channel.ObtenerEstado(pIdOferta)
        End Function
        
        Public Function ConsultarEstados(ByVal pIdOferta As Long) As System.Data.DataSet Implements ListaOfertaCabService.IListaOfertaCabService.ConsultarEstados
            Return MyBase.Channel.ConsultarEstados(pIdOferta)
        End Function
        
        Public Function MostrarEstados() As System.Data.DataSet Implements ListaOfertaCabService.IListaOfertaCabService.MostrarEstados
            Return MyBase.Channel.MostrarEstados
        End Function
        
        Public Function VencimientoPrecio(ByVal pIdOferta As Long, ByVal pObservacion As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.VencimientoPrecio
            Return MyBase.Channel.VencimientoPrecio(pIdOferta, pObservacion, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function MostrarPendientes(ByVal pIdOferta As Long) As System.Data.DataSet Implements ListaOfertaCabService.IListaOfertaCabService.MostrarPendientes
            Return MyBase.Channel.MostrarPendientes(pIdOferta)
        End Function
        
        Public Function BuscarAprobacionPendiente(ByVal pIdOferta As Long) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.BuscarAprobacionPendiente
            Return MyBase.Channel.BuscarAprobacionPendiente(pIdOferta)
        End Function
        
        Public Function Imprimir(ByVal pIdOferta As Long) As System.Data.DataSet Implements ListaOfertaCabService.IListaOfertaCabService.Imprimir
            Return MyBase.Channel.Imprimir(pIdOferta)
        End Function
        
        Public Function ActualizarFechaVencimiento(ByVal pIdOferta As Long, ByVal pFecVencimiento As Date, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements ListaOfertaCabService.IListaOfertaCabService.ActualizarFechaVencimiento
            Return MyBase.Channel.ActualizarFechaVencimiento(pIdOferta, pFecVencimiento, pCodUsu, pNomPc, pDirIp)
        End Function
    End Class
End Namespace
