'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace HorarioDetService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HorarioDet", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class HorarioDet
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesDiaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiaHorField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HorIngField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HorSalField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HorarioField As HorarioDetService.Horario
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IngRefField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SalRefField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesDia() As String
            Get
                Return Me.DesDiaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesDiaField, value) <> true) Then
                    Me.DesDiaField = value
                    Me.RaisePropertyChanged("DesDia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DiaHor() As Integer
            Get
                Return Me.DiaHorField
            End Get
            Set
                If (Me.DiaHorField.Equals(value) <> true) Then
                    Me.DiaHorField = value
                    Me.RaisePropertyChanged("DiaHor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HorIng() As Date
            Get
                Return Me.HorIngField
            End Get
            Set
                If (Me.HorIngField.Equals(value) <> true) Then
                    Me.HorIngField = value
                    Me.RaisePropertyChanged("HorIng")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HorSal() As Date
            Get
                Return Me.HorSalField
            End Get
            Set
                If (Me.HorSalField.Equals(value) <> true) Then
                    Me.HorSalField = value
                    Me.RaisePropertyChanged("HorSal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Horario() As HorarioDetService.Horario
            Get
                Return Me.HorarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HorarioField, value) <> true) Then
                    Me.HorarioField = value
                    Me.RaisePropertyChanged("Horario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IngRef() As Date
            Get
                Return Me.IngRefField
            End Get
            Set
                If (Me.IngRefField.Equals(value) <> true) Then
                    Me.IngRefField = value
                    Me.RaisePropertyChanged("IngRef")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SalRef() As Date
            Get
                Return Me.SalRefField
            End Get
            Set
                If (Me.SalRefField.Equals(value) <> true) Then
                    Me.SalRefField = value
                    Me.RaisePropertyChanged("SalRef")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Horario", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Horario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AplicaTardanzaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodHorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesHorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As HorarioDetService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FeriadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TieRefField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TolIngField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TolRefField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotHoraNormalField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TurnoField As HorarioDetService.Turno
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VigenteField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AplicaTardanza() As Boolean
            Get
                Return Me.AplicaTardanzaField
            End Get
            Set
                If (Me.AplicaTardanzaField.Equals(value) <> true) Then
                    Me.AplicaTardanzaField = value
                    Me.RaisePropertyChanged("AplicaTardanza")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodHor() As String
            Get
                Return Me.CodHorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodHorField, value) <> true) Then
                    Me.CodHorField = value
                    Me.RaisePropertyChanged("CodHor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesHor() As String
            Get
                Return Me.DesHorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesHorField, value) <> true) Then
                    Me.DesHorField = value
                    Me.RaisePropertyChanged("DesHor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As HorarioDetService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Feriado() As Boolean
            Get
                Return Me.FeriadoField
            End Get
            Set
                If (Me.FeriadoField.Equals(value) <> true) Then
                    Me.FeriadoField = value
                    Me.RaisePropertyChanged("Feriado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TieRef() As Double
            Get
                Return Me.TieRefField
            End Get
            Set
                If (Me.TieRefField.Equals(value) <> true) Then
                    Me.TieRefField = value
                    Me.RaisePropertyChanged("TieRef")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TolIng() As Double
            Get
                Return Me.TolIngField
            End Get
            Set
                If (Me.TolIngField.Equals(value) <> true) Then
                    Me.TolIngField = value
                    Me.RaisePropertyChanged("TolIng")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TolRef() As Double
            Get
                Return Me.TolRefField
            End Get
            Set
                If (Me.TolRefField.Equals(value) <> true) Then
                    Me.TolRefField = value
                    Me.RaisePropertyChanged("TolRef")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotHoraNormal() As Decimal
            Get
                Return Me.TotHoraNormalField
            End Get
            Set
                If (Me.TotHoraNormalField.Equals(value) <> true) Then
                    Me.TotHoraNormalField = value
                    Me.RaisePropertyChanged("TotHoraNormal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Turno() As HorarioDetService.Turno
            Get
                Return Me.TurnoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TurnoField, value) <> true) Then
                    Me.TurnoField = value
                    Me.RaisePropertyChanged("Turno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vigente() As Boolean
            Get
                Return Me.VigenteField
            End Get
            Set
                If (Me.VigenteField.Equals(value) <> true) Then
                    Me.VigenteField = value
                    Me.RaisePropertyChanged("Vigente")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AplicaOSEField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UbigeoField As HorarioDetService.Ubigeo
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AplicaOSE() As Boolean
            Get
                Return Me.AplicaOSEField
            End Get
            Set
                If (Me.AplicaOSEField.Equals(value) <> true) Then
                    Me.AplicaOSEField = value
                    Me.RaisePropertyChanged("AplicaOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCertificado() As String
            Get
                Return Me.ClaveCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCertificadoField, value) <> true) Then
                    Me.ClaveCertificadoField = value
                    Me.RaisePropertyChanged("ClaveCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCorreoEmisor() As String
            Get
                Return Me.ClaveCorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCorreoEmisorField, value) <> true) Then
                    Me.ClaveCorreoEmisorField = value
                    Me.RaisePropertyChanged("ClaveCorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveOSE() As String
            Get
                Return Me.ClaveOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveOSEField, value) <> true) Then
                    Me.ClaveOSEField = value
                    Me.RaisePropertyChanged("ClaveOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSOL() As String
            Get
                Return Me.ClaveSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSOLField, value) <> true) Then
                    Me.ClaveSOLField = value
                    Me.RaisePropertyChanged("ClaveSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorreoEmisor() As String
            Get
                Return Me.CorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorreoEmisorField, value) <> true) Then
                    Me.CorreoEmisorField = value
                    Me.RaisePropertyChanged("CorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Logo() As Byte()
            Get
                Return Me.LogoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoField, value) <> true) Then
                    Me.LogoField = value
                    Me.RaisePropertyChanged("Logo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailHost() As String
            Get
                Return Me.MailHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailHostField, value) <> true) Then
                    Me.MailHostField = value
                    Me.RaisePropertyChanged("MailHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCertificado() As String
            Get
                Return Me.NombreCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCertificadoField, value) <> true) Then
                    Me.NombreCertificadoField = value
                    Me.RaisePropertyChanged("NombreCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ubigeo() As HorarioDetService.Ubigeo
            Get
                Return Me.UbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UbigeoField, value) <> true) Then
                    Me.UbigeoField = value
                    Me.RaisePropertyChanged("Ubigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioOSE() As String
            Get
                Return Me.UsuarioOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioOSEField, value) <> true) Then
                    Me.UsuarioOSEField = value
                    Me.RaisePropertyChanged("UsuarioOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioSOL() As String
            Get
                Return Me.UsuarioSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioSOLField, value) <> true) Then
                    Me.UsuarioSOLField = value
                    Me.RaisePropertyChanged("UsuarioSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Turno", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Turno
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesTurnoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTurnoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesTurno() As String
            Get
                Return Me.DesTurnoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesTurnoField, value) <> true) Then
                    Me.DesTurnoField = value
                    Me.RaisePropertyChanged("DesTurno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTurno() As Integer
            Get
                Return Me.IdTurnoField
            End Get
            Set
                If (Me.IdTurnoField.Equals(value) <> true) Then
                    Me.IdTurnoField = value
                    Me.RaisePropertyChanged("IdTurno")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ubigeo", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ubigeo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUbigeoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As HorarioDetService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistritoField As HorarioDetService.Distrito
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As HorarioDetService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUbigeo() As String
            Get
                Return Me.CodUbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUbigeoField, value) <> true) Then
                    Me.CodUbigeoField = value
                    Me.RaisePropertyChanged("CodUbigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As HorarioDetService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Distrito() As HorarioDetService.Distrito
            Get
                Return Me.DistritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistritoField, value) <> true) Then
                    Me.DistritoField = value
                    Me.RaisePropertyChanged("Distrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As HorarioDetService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Departamento", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Departamento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDptoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDptoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDpto() As String
            Get
                Return Me.CodDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDptoField, value) <> true) Then
                    Me.CodDptoField = value
                    Me.RaisePropertyChanged("CodDpto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDpto() As String
            Get
                Return Me.NomDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDptoField, value) <> true) Then
                    Me.NomDptoField = value
                    Me.RaisePropertyChanged("NomDpto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Distrito", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Distrito
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As HorarioDetService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDist() As String
            Get
                Return Me.CodDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDistField, value) <> true) Then
                    Me.CodDistField = value
                    Me.RaisePropertyChanged("CodDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDist() As String
            Get
                Return Me.NomDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDistField, value) <> true) Then
                    Me.NomDistField = value
                    Me.RaisePropertyChanged("NomDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As HorarioDetService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Provincia", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Provincia
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodProvField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As HorarioDetService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomProvField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodProv() As String
            Get
                Return Me.CodProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodProvField, value) <> true) Then
                    Me.CodProvField = value
                    Me.RaisePropertyChanged("CodProv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As HorarioDetService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomProv() As String
            Get
                Return Me.NomProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomProvField, value) <> true) Then
                    Me.NomProvField = value
                    Me.RaisePropertyChanged("NomProv")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HorarioDetService.IHorarioDetService")>  _
    Public Interface IHorarioDetService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Obtener", ReplyAction:="http://tempuri.org/IHorarioDetService/ObtenerResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Obtener(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer) As HorarioDetService.HorarioDet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Buscar", ReplyAction:="http://tempuri.org/IHorarioDetService/BuscarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Buscar(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Mostrar", ReplyAction:="http://tempuri.org/IHorarioDetService/MostrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Mostrar(ByVal pCodHor As String, ByVal pCodEmp As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Insertar", ReplyAction:="http://tempuri.org/IHorarioDetService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Registro As HorarioDetService.HorarioDet) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Actualizar", ReplyAction:="http://tempuri.org/IHorarioDetService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Registro As HorarioDetService.HorarioDet) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorarioDetService/Borrar", ReplyAction:="http://tempuri.org/IHorarioDetService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(HorarioDetService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHorarioDetServiceChannel
        Inherits HorarioDetService.IHorarioDetService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HorarioDetServiceClient
        Inherits System.ServiceModel.ClientBase(Of HorarioDetService.IHorarioDetService)
        Implements HorarioDetService.IHorarioDetService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Obtener(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer) As HorarioDetService.HorarioDet Implements HorarioDetService.IHorarioDetService.Obtener
            Return MyBase.Channel.Obtener(pCodHor, pCodEmp, pDiaHor)
        End Function
        
        Public Function Buscar(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer) As Boolean Implements HorarioDetService.IHorarioDetService.Buscar
            Return MyBase.Channel.Buscar(pCodHor, pCodEmp, pDiaHor)
        End Function
        
        Public Function Mostrar(ByVal pCodHor As String, ByVal pCodEmp As String) As System.Data.DataSet Implements HorarioDetService.IHorarioDetService.Mostrar
            Return MyBase.Channel.Mostrar(pCodHor, pCodEmp)
        End Function
        
        Public Function Insertar(ByVal Registro As HorarioDetService.HorarioDet) As Boolean Implements HorarioDetService.IHorarioDetService.Insertar
            Return MyBase.Channel.Insertar(Registro)
        End Function
        
        Public Function Actualizar(ByVal Registro As HorarioDetService.HorarioDet) As Boolean Implements HorarioDetService.IHorarioDetService.Actualizar
            Return MyBase.Channel.Actualizar(Registro)
        End Function
        
        Public Function Borrar(ByVal pCodHor As String, ByVal pCodEmp As String, ByVal pDiaHor As Integer, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements HorarioDetService.IHorarioDetService.Borrar
            Return MyBase.Channel.Borrar(pCodHor, pCodEmp, pDiaHor, pCodUsu, pNomPc, pDirIp)
        End Function
    End Class
End Namespace
