'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace FlujoCajaCabService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FlujoCajaCab", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FlujoCajaCab
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As FlujoCajaCabService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoFlujoCajaField As FlujoCajaCabService.EstadoFlujoCaja
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FecRegField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdFlujoCajaField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonedaField As FlujoCajaCabService.Moneda
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PeriodoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SaldoInicioField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalIngresoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalSaldoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalSalidaField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As FlujoCajaCabService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoFlujoCaja() As FlujoCajaCabService.EstadoFlujoCaja
            Get
                Return Me.EstadoFlujoCajaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoFlujoCajaField, value) <> true) Then
                    Me.EstadoFlujoCajaField = value
                    Me.RaisePropertyChanged("EstadoFlujoCaja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FecReg() As Date
            Get
                Return Me.FecRegField
            End Get
            Set
                If (Me.FecRegField.Equals(value) <> true) Then
                    Me.FecRegField = value
                    Me.RaisePropertyChanged("FecReg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdFlujoCaja() As Long
            Get
                Return Me.IdFlujoCajaField
            End Get
            Set
                If (Me.IdFlujoCajaField.Equals(value) <> true) Then
                    Me.IdFlujoCajaField = value
                    Me.RaisePropertyChanged("IdFlujoCaja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mes() As Integer
            Get
                Return Me.MesField
            End Get
            Set
                If (Me.MesField.Equals(value) <> true) Then
                    Me.MesField = value
                    Me.RaisePropertyChanged("Mes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Moneda() As FlujoCajaCabService.Moneda
            Get
                Return Me.MonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonedaField, value) <> true) Then
                    Me.MonedaField = value
                    Me.RaisePropertyChanged("Moneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Periodo() As Integer
            Get
                Return Me.PeriodoField
            End Get
            Set
                If (Me.PeriodoField.Equals(value) <> true) Then
                    Me.PeriodoField = value
                    Me.RaisePropertyChanged("Periodo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SaldoInicio() As Double
            Get
                Return Me.SaldoInicioField
            End Get
            Set
                If (Me.SaldoInicioField.Equals(value) <> true) Then
                    Me.SaldoInicioField = value
                    Me.RaisePropertyChanged("SaldoInicio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalIngreso() As Double
            Get
                Return Me.TotalIngresoField
            End Get
            Set
                If (Me.TotalIngresoField.Equals(value) <> true) Then
                    Me.TotalIngresoField = value
                    Me.RaisePropertyChanged("TotalIngreso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalSaldo() As Double
            Get
                Return Me.TotalSaldoField
            End Get
            Set
                If (Me.TotalSaldoField.Equals(value) <> true) Then
                    Me.TotalSaldoField = value
                    Me.RaisePropertyChanged("TotalSaldo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalSalida() As Double
            Get
                Return Me.TotalSalidaField
            End Get
            Set
                If (Me.TotalSalidaField.Equals(value) <> true) Then
                    Me.TotalSalidaField = value
                    Me.RaisePropertyChanged("TotalSalida")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AplicaOSEField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UbigeoField As FlujoCajaCabService.Ubigeo
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AplicaOSE() As Boolean
            Get
                Return Me.AplicaOSEField
            End Get
            Set
                If (Me.AplicaOSEField.Equals(value) <> true) Then
                    Me.AplicaOSEField = value
                    Me.RaisePropertyChanged("AplicaOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCertificado() As String
            Get
                Return Me.ClaveCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCertificadoField, value) <> true) Then
                    Me.ClaveCertificadoField = value
                    Me.RaisePropertyChanged("ClaveCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCorreoEmisor() As String
            Get
                Return Me.ClaveCorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCorreoEmisorField, value) <> true) Then
                    Me.ClaveCorreoEmisorField = value
                    Me.RaisePropertyChanged("ClaveCorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveOSE() As String
            Get
                Return Me.ClaveOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveOSEField, value) <> true) Then
                    Me.ClaveOSEField = value
                    Me.RaisePropertyChanged("ClaveOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSOL() As String
            Get
                Return Me.ClaveSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSOLField, value) <> true) Then
                    Me.ClaveSOLField = value
                    Me.RaisePropertyChanged("ClaveSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorreoEmisor() As String
            Get
                Return Me.CorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorreoEmisorField, value) <> true) Then
                    Me.CorreoEmisorField = value
                    Me.RaisePropertyChanged("CorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Logo() As Byte()
            Get
                Return Me.LogoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoField, value) <> true) Then
                    Me.LogoField = value
                    Me.RaisePropertyChanged("Logo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailHost() As String
            Get
                Return Me.MailHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailHostField, value) <> true) Then
                    Me.MailHostField = value
                    Me.RaisePropertyChanged("MailHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCertificado() As String
            Get
                Return Me.NombreCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCertificadoField, value) <> true) Then
                    Me.NombreCertificadoField = value
                    Me.RaisePropertyChanged("NombreCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ubigeo() As FlujoCajaCabService.Ubigeo
            Get
                Return Me.UbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UbigeoField, value) <> true) Then
                    Me.UbigeoField = value
                    Me.RaisePropertyChanged("Ubigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioOSE() As String
            Get
                Return Me.UsuarioOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioOSEField, value) <> true) Then
                    Me.UsuarioOSEField = value
                    Me.RaisePropertyChanged("UsuarioOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioSOL() As String
            Get
                Return Me.UsuarioSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioSOLField, value) <> true) Then
                    Me.UsuarioSOLField = value
                    Me.RaisePropertyChanged("UsuarioSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoFlujoCaja", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoFlujoCaja
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdEstadoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEstado() As String
            Get
                Return Me.AbrEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEstadoField, value) <> true) Then
                    Me.AbrEstadoField = value
                    Me.RaisePropertyChanged("AbrEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEstado() As String
            Get
                Return Me.DesEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEstadoField, value) <> true) Then
                    Me.DesEstadoField = value
                    Me.RaisePropertyChanged("DesEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdEstado() As Integer
            Get
                Return Me.IdEstadoField
            End Get
            Set
                If (Me.IdEstadoField.Equals(value) <> true) Then
                    Me.IdEstadoField = value
                    Me.RaisePropertyChanged("IdEstado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Moneda", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Moneda
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodMonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesMonField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrMon() As String
            Get
                Return Me.AbrMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrMonField, value) <> true) Then
                    Me.AbrMonField = value
                    Me.RaisePropertyChanged("AbrMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodMon() As String
            Get
                Return Me.CodMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodMonField, value) <> true) Then
                    Me.CodMonField = value
                    Me.RaisePropertyChanged("CodMon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesMon() As String
            Get
                Return Me.DesMonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesMonField, value) <> true) Then
                    Me.DesMonField = value
                    Me.RaisePropertyChanged("DesMon")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ubigeo", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ubigeo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUbigeoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As FlujoCajaCabService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistritoField As FlujoCajaCabService.Distrito
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As FlujoCajaCabService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUbigeo() As String
            Get
                Return Me.CodUbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUbigeoField, value) <> true) Then
                    Me.CodUbigeoField = value
                    Me.RaisePropertyChanged("CodUbigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As FlujoCajaCabService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Distrito() As FlujoCajaCabService.Distrito
            Get
                Return Me.DistritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistritoField, value) <> true) Then
                    Me.DistritoField = value
                    Me.RaisePropertyChanged("Distrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As FlujoCajaCabService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Departamento", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Departamento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDptoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDptoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDpto() As String
            Get
                Return Me.CodDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDptoField, value) <> true) Then
                    Me.CodDptoField = value
                    Me.RaisePropertyChanged("CodDpto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDpto() As String
            Get
                Return Me.NomDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDptoField, value) <> true) Then
                    Me.NomDptoField = value
                    Me.RaisePropertyChanged("NomDpto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Distrito", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Distrito
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As FlujoCajaCabService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDist() As String
            Get
                Return Me.CodDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDistField, value) <> true) Then
                    Me.CodDistField = value
                    Me.RaisePropertyChanged("CodDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDist() As String
            Get
                Return Me.NomDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDistField, value) <> true) Then
                    Me.NomDistField = value
                    Me.RaisePropertyChanged("NomDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As FlujoCajaCabService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Provincia", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Provincia
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodProvField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As FlujoCajaCabService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomProvField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodProv() As String
            Get
                Return Me.CodProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodProvField, value) <> true) Then
                    Me.CodProvField = value
                    Me.RaisePropertyChanged("CodProv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As FlujoCajaCabService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomProv() As String
            Get
                Return Me.NomProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomProvField, value) <> true) Then
                    Me.NomProvField = value
                    Me.RaisePropertyChanged("NomProv")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FlujoCajaCabService.IFlujoCajaCabService")>  _
    Public Interface IFlujoCajaCabService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Obtener", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ObtenerResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Obtener(ByVal pIdFlujoCaja As Long) As FlujoCajaCabService.FlujoCajaCab
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Obtener", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ObtenerResponse")>  _
        Function ObtenerAsync(ByVal pIdFlujoCaja As Long) As System.Threading.Tasks.Task(Of FlujoCajaCabService.FlujoCajaCab)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Filtrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/FiltrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Filtrar(ByVal pCodEmp As String, ByVal pPeriodo As Integer, ByVal pMes As Integer, ByVal pIdEstado As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Filtrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal pCodEmp As String, ByVal pPeriodo As Integer, ByVal pMes As Integer, ByVal pIdEstado As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Insertar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Insertar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/InsertarResponse")>  _
        Function InsertarAsync(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As System.Threading.Tasks.Task(Of Long)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Actualizar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Actualizar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ActualizarResponse")>  _
        Function ActualizarAsync(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Borrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Borrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/BorrarResponse")>  _
        Function BorrarAsync(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Imprimir", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ImprimirResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Imprimir(ByVal pIdFlujoCaja As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Imprimir", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ImprimirResponse")>  _
        Function ImprimirAsync(ByVal pIdFlujoCaja As Long) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/ConsultarEstados", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ConsultarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ConsultarEstados(ByVal pIdFlujoCaja As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/ConsultarEstados", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ConsultarEstadosResponse")>  _
        Function ConsultarEstadosAsync(ByVal pIdFlujoCaja As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/ObtenerEstado", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ObtenerEstadoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function ObtenerEstado(ByVal pIdFlujoCaja As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/ObtenerEstado", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/ObtenerEstadoResponse")>  _
        Function ObtenerEstadoAsync(ByVal pIdFlujoCaja As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/MostrarEstados", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/MostrarEstadosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function MostrarEstados() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/MostrarEstados", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/MostrarEstadosResponse")>  _
        Function MostrarEstadosAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Cerrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/CerrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(FlujoCajaCabService.MiError), Action:="http://www.ddperu.com.pe/MyError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Cerrar(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFlujoCajaCabService/Cerrar", ReplyAction:="http://tempuri.org/IFlujoCajaCabService/CerrarResponse")>  _
        Function CerrarAsync(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IFlujoCajaCabServiceChannel
        Inherits FlujoCajaCabService.IFlujoCajaCabService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FlujoCajaCabServiceClient
        Inherits System.ServiceModel.ClientBase(Of FlujoCajaCabService.IFlujoCajaCabService)
        Implements FlujoCajaCabService.IFlujoCajaCabService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Obtener(ByVal pIdFlujoCaja As Long) As FlujoCajaCabService.FlujoCajaCab Implements FlujoCajaCabService.IFlujoCajaCabService.Obtener
            Return MyBase.Channel.Obtener(pIdFlujoCaja)
        End Function
        
        Public Function ObtenerAsync(ByVal pIdFlujoCaja As Long) As System.Threading.Tasks.Task(Of FlujoCajaCabService.FlujoCajaCab) Implements FlujoCajaCabService.IFlujoCajaCabService.ObtenerAsync
            Return MyBase.Channel.ObtenerAsync(pIdFlujoCaja)
        End Function
        
        Public Function Filtrar(ByVal pCodEmp As String, ByVal pPeriodo As Integer, ByVal pMes As Integer, ByVal pIdEstado As Integer) As System.Data.DataSet Implements FlujoCajaCabService.IFlujoCajaCabService.Filtrar
            Return MyBase.Channel.Filtrar(pCodEmp, pPeriodo, pMes, pIdEstado)
        End Function
        
        Public Function FiltrarAsync(ByVal pCodEmp As String, ByVal pPeriodo As Integer, ByVal pMes As Integer, ByVal pIdEstado As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FlujoCajaCabService.IFlujoCajaCabService.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(pCodEmp, pPeriodo, pMes, pIdEstado)
        End Function
        
        Public Function Insertar(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As Long Implements FlujoCajaCabService.IFlujoCajaCabService.Insertar
            Return MyBase.Channel.Insertar(Registro)
        End Function
        
        Public Function InsertarAsync(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As System.Threading.Tasks.Task(Of Long) Implements FlujoCajaCabService.IFlujoCajaCabService.InsertarAsync
            Return MyBase.Channel.InsertarAsync(Registro)
        End Function
        
        Public Function Actualizar(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As Boolean Implements FlujoCajaCabService.IFlujoCajaCabService.Actualizar
            Return MyBase.Channel.Actualizar(Registro)
        End Function
        
        Public Function ActualizarAsync(ByVal Registro As FlujoCajaCabService.FlujoCajaCab) As System.Threading.Tasks.Task(Of Boolean) Implements FlujoCajaCabService.IFlujoCajaCabService.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(Registro)
        End Function
        
        Public Function Borrar(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements FlujoCajaCabService.IFlujoCajaCabService.Borrar
            Return MyBase.Channel.Borrar(pIdFlujoCaja, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function BorrarAsync(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean) Implements FlujoCajaCabService.IFlujoCajaCabService.BorrarAsync
            Return MyBase.Channel.BorrarAsync(pIdFlujoCaja, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function Imprimir(ByVal pIdFlujoCaja As Long) As System.Data.DataSet Implements FlujoCajaCabService.IFlujoCajaCabService.Imprimir
            Return MyBase.Channel.Imprimir(pIdFlujoCaja)
        End Function
        
        Public Function ImprimirAsync(ByVal pIdFlujoCaja As Long) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FlujoCajaCabService.IFlujoCajaCabService.ImprimirAsync
            Return MyBase.Channel.ImprimirAsync(pIdFlujoCaja)
        End Function
        
        Public Function ConsultarEstados(ByVal pIdFlujoCaja As Integer) As System.Data.DataSet Implements FlujoCajaCabService.IFlujoCajaCabService.ConsultarEstados
            Return MyBase.Channel.ConsultarEstados(pIdFlujoCaja)
        End Function
        
        Public Function ConsultarEstadosAsync(ByVal pIdFlujoCaja As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FlujoCajaCabService.IFlujoCajaCabService.ConsultarEstadosAsync
            Return MyBase.Channel.ConsultarEstadosAsync(pIdFlujoCaja)
        End Function
        
        Public Function ObtenerEstado(ByVal pIdFlujoCaja As Integer) As Integer Implements FlujoCajaCabService.IFlujoCajaCabService.ObtenerEstado
            Return MyBase.Channel.ObtenerEstado(pIdFlujoCaja)
        End Function
        
        Public Function ObtenerEstadoAsync(ByVal pIdFlujoCaja As Integer) As System.Threading.Tasks.Task(Of Integer) Implements FlujoCajaCabService.IFlujoCajaCabService.ObtenerEstadoAsync
            Return MyBase.Channel.ObtenerEstadoAsync(pIdFlujoCaja)
        End Function
        
        Public Function MostrarEstados() As System.Data.DataSet Implements FlujoCajaCabService.IFlujoCajaCabService.MostrarEstados
            Return MyBase.Channel.MostrarEstados
        End Function
        
        Public Function MostrarEstadosAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FlujoCajaCabService.IFlujoCajaCabService.MostrarEstadosAsync
            Return MyBase.Channel.MostrarEstadosAsync
        End Function
        
        Public Function Cerrar(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements FlujoCajaCabService.IFlujoCajaCabService.Cerrar
            Return MyBase.Channel.Cerrar(pIdFlujoCaja, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function CerrarAsync(ByVal pIdFlujoCaja As Long, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean) Implements FlujoCajaCabService.IFlujoCajaCabService.CerrarAsync
            Return MyBase.Channel.CerrarAsync(pIdFlujoCaja, pCodUsu, pNomPc, pDirIp)
        End Function
    End Class
End Namespace
