'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace TipoMotorProductoService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MiError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoMotorProducto", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoMotorProducto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUsuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirIpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As TipoMotorProductoService.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomPcField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipMotField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUsu() As String
            Get
                Return Me.CodUsuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUsuField, value) <> true) Then
                    Me.CodUsuField = value
                    Me.RaisePropertyChanged("CodUsu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirIp() As String
            Get
                Return Me.DirIpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirIpField, value) <> true) Then
                    Me.DirIpField = value
                    Me.RaisePropertyChanged("DirIp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As TipoMotorProductoService.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomPc() As String
            Get
                Return Me.NomPcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomPcField, value) <> true) Then
                    Me.NomPcField = value
                    Me.RaisePropertyChanged("NomPc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipMot() As String
            Get
                Return Me.TipMotField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipMotField, value) <> true) Then
                    Me.TipMotField = value
                    Me.RaisePropertyChanged("TipMot")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AbrEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AplicaOSEField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CorreoEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DesEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DirEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IgvField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogoField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MailHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RucEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelEmpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UbigeoField As TipoMotorProductoService.Ubigeo
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioOSEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioSOLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebEmpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AbrEmp() As String
            Get
                Return Me.AbrEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AbrEmpField, value) <> true) Then
                    Me.AbrEmpField = value
                    Me.RaisePropertyChanged("AbrEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AplicaOSE() As Boolean
            Get
                Return Me.AplicaOSEField
            End Get
            Set
                If (Me.AplicaOSEField.Equals(value) <> true) Then
                    Me.AplicaOSEField = value
                    Me.RaisePropertyChanged("AplicaOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCertificado() As String
            Get
                Return Me.ClaveCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCertificadoField, value) <> true) Then
                    Me.ClaveCertificadoField = value
                    Me.RaisePropertyChanged("ClaveCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCorreoEmisor() As String
            Get
                Return Me.ClaveCorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCorreoEmisorField, value) <> true) Then
                    Me.ClaveCorreoEmisorField = value
                    Me.RaisePropertyChanged("ClaveCorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveOSE() As String
            Get
                Return Me.ClaveOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveOSEField, value) <> true) Then
                    Me.ClaveOSEField = value
                    Me.RaisePropertyChanged("ClaveOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSOL() As String
            Get
                Return Me.ClaveSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSOLField, value) <> true) Then
                    Me.ClaveSOLField = value
                    Me.RaisePropertyChanged("ClaveSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmp() As String
            Get
                Return Me.CodEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEmpField, value) <> true) Then
                    Me.CodEmpField = value
                    Me.RaisePropertyChanged("CodEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorEmp() As String
            Get
                Return Me.CorEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorEmpField, value) <> true) Then
                    Me.CorEmpField = value
                    Me.RaisePropertyChanged("CorEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CorreoEmisor() As String
            Get
                Return Me.CorreoEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CorreoEmisorField, value) <> true) Then
                    Me.CorreoEmisorField = value
                    Me.RaisePropertyChanged("CorreoEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DesEmp() As String
            Get
                Return Me.DesEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DesEmpField, value) <> true) Then
                    Me.DesEmpField = value
                    Me.RaisePropertyChanged("DesEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DirEmp() As String
            Get
                Return Me.DirEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DirEmpField, value) <> true) Then
                    Me.DirEmpField = value
                    Me.RaisePropertyChanged("DirEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaxEmp() As String
            Get
                Return Me.FaxEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxEmpField, value) <> true) Then
                    Me.FaxEmpField = value
                    Me.RaisePropertyChanged("FaxEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Igv() As Integer
            Get
                Return Me.IgvField
            End Get
            Set
                If (Me.IgvField.Equals(value) <> true) Then
                    Me.IgvField = value
                    Me.RaisePropertyChanged("Igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Logo() As Byte()
            Get
                Return Me.LogoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogoField, value) <> true) Then
                    Me.LogoField = value
                    Me.RaisePropertyChanged("Logo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MailHost() As String
            Get
                Return Me.MailHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MailHostField, value) <> true) Then
                    Me.MailHostField = value
                    Me.RaisePropertyChanged("MailHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCertificado() As String
            Get
                Return Me.NombreCertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCertificadoField, value) <> true) Then
                    Me.NombreCertificadoField = value
                    Me.RaisePropertyChanged("NombreCertificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RucEmp() As String
            Get
                Return Me.RucEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RucEmpField, value) <> true) Then
                    Me.RucEmpField = value
                    Me.RaisePropertyChanged("RucEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TelEmp() As String
            Get
                Return Me.TelEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelEmpField, value) <> true) Then
                    Me.TelEmpField = value
                    Me.RaisePropertyChanged("TelEmp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ubigeo() As TipoMotorProductoService.Ubigeo
            Get
                Return Me.UbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UbigeoField, value) <> true) Then
                    Me.UbigeoField = value
                    Me.RaisePropertyChanged("Ubigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioOSE() As String
            Get
                Return Me.UsuarioOSEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioOSEField, value) <> true) Then
                    Me.UsuarioOSEField = value
                    Me.RaisePropertyChanged("UsuarioOSE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioSOL() As String
            Get
                Return Me.UsuarioSOLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioSOLField, value) <> true) Then
                    Me.UsuarioSOLField = value
                    Me.RaisePropertyChanged("UsuarioSOL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WebEmp() As String
            Get
                Return Me.WebEmpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebEmpField, value) <> true) Then
                    Me.WebEmpField = value
                    Me.RaisePropertyChanged("WebEmp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ubigeo", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ubigeo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodUbigeoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As TipoMotorProductoService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistritoField As TipoMotorProductoService.Distrito
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As TipoMotorProductoService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodUbigeo() As String
            Get
                Return Me.CodUbigeoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodUbigeoField, value) <> true) Then
                    Me.CodUbigeoField = value
                    Me.RaisePropertyChanged("CodUbigeo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As TipoMotorProductoService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Distrito() As TipoMotorProductoService.Distrito
            Get
                Return Me.DistritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistritoField, value) <> true) Then
                    Me.DistritoField = value
                    Me.RaisePropertyChanged("Distrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As TipoMotorProductoService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Departamento", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Departamento
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDptoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDptoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDpto() As String
            Get
                Return Me.CodDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDptoField, value) <> true) Then
                    Me.CodDptoField = value
                    Me.RaisePropertyChanged("CodDpto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDpto() As String
            Get
                Return Me.NomDptoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDptoField, value) <> true) Then
                    Me.NomDptoField = value
                    Me.RaisePropertyChanged("NomDpto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Distrito", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Distrito
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomDistField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As TipoMotorProductoService.Provincia
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodDist() As String
            Get
                Return Me.CodDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodDistField, value) <> true) Then
                    Me.CodDistField = value
                    Me.RaisePropertyChanged("CodDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomDist() As String
            Get
                Return Me.NomDistField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomDistField, value) <> true) Then
                    Me.NomDistField = value
                    Me.RaisePropertyChanged("NomDist")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Provincia() As TipoMotorProductoService.Provincia
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Provincia", [Namespace]:="http://schemas.datacontract.org/2004/07/Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Provincia
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodProvField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As TipoMotorProductoService.Departamento
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomProvField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodProv() As String
            Get
                Return Me.CodProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodProvField, value) <> true) Then
                    Me.CodProvField = value
                    Me.RaisePropertyChanged("CodProv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As TipoMotorProductoService.Departamento
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NomProv() As String
            Get
                Return Me.NomProvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomProvField, value) <> true) Then
                    Me.NomProvField = value
                    Me.RaisePropertyChanged("NomProv")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="TipoMotorProductoService.ITipoMotorProductoService")>  _
    Public Interface ITipoMotorProductoService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Mostrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/MostrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Mostrar(ByVal pCodEmp As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Mostrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/MostrarResponse")>  _
        Function MostrarAsync(ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Filtrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/FiltrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Filtrar(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pDescripcion As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Filtrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pDescripcion As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Obtener", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/ObtenerResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Obtener(ByVal pTipMot As String, ByVal pCodEmp As String) As TipoMotorProductoService.TipoMotorProducto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Obtener", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/ObtenerResponse")>  _
        Function ObtenerAsync(ByVal pTipMot As String, ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of TipoMotorProductoService.TipoMotorProducto)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Buscar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/BuscarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Buscar(ByVal pTipMot As String, ByVal pCodEmp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Buscar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/BuscarResponse")>  _
        Function BuscarAsync(ByVal pTipMot As String, ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Insertar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/InsertarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Insertar(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Insertar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/InsertarResponse")>  _
        Function InsertarAsync(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Actualizar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/ActualizarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Actualizar(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Actualizar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/ActualizarResponse")>  _
        Function ActualizarAsync(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Borrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/BorrarResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TipoMotorProductoService.MiError), Action:="http://www.ddperu.com.pe/MiError", Name:="MiError", [Namespace]:="http://schemas.datacontract.org/2004/07/ServicioBLL")>  _
        Function Borrar(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITipoMotorProductoService/Borrar", ReplyAction:="http://tempuri.org/ITipoMotorProductoService/BorrarResponse")>  _
        Function BorrarAsync(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITipoMotorProductoServiceChannel
        Inherits TipoMotorProductoService.ITipoMotorProductoService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TipoMotorProductoServiceClient
        Inherits System.ServiceModel.ClientBase(Of TipoMotorProductoService.ITipoMotorProductoService)
        Implements TipoMotorProductoService.ITipoMotorProductoService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Mostrar(ByVal pCodEmp As String) As System.Data.DataSet Implements TipoMotorProductoService.ITipoMotorProductoService.Mostrar
            Return MyBase.Channel.Mostrar(pCodEmp)
        End Function
        
        Public Function MostrarAsync(ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements TipoMotorProductoService.ITipoMotorProductoService.MostrarAsync
            Return MyBase.Channel.MostrarAsync(pCodEmp)
        End Function
        
        Public Function Filtrar(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pDescripcion As String) As System.Data.DataSet Implements TipoMotorProductoService.ITipoMotorProductoService.Filtrar
            Return MyBase.Channel.Filtrar(pTipMot, pCodEmp, pDescripcion)
        End Function
        
        Public Function FiltrarAsync(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pDescripcion As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements TipoMotorProductoService.ITipoMotorProductoService.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(pTipMot, pCodEmp, pDescripcion)
        End Function
        
        Public Function Obtener(ByVal pTipMot As String, ByVal pCodEmp As String) As TipoMotorProductoService.TipoMotorProducto Implements TipoMotorProductoService.ITipoMotorProductoService.Obtener
            Return MyBase.Channel.Obtener(pTipMot, pCodEmp)
        End Function
        
        Public Function ObtenerAsync(ByVal pTipMot As String, ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of TipoMotorProductoService.TipoMotorProducto) Implements TipoMotorProductoService.ITipoMotorProductoService.ObtenerAsync
            Return MyBase.Channel.ObtenerAsync(pTipMot, pCodEmp)
        End Function
        
        Public Function Buscar(ByVal pTipMot As String, ByVal pCodEmp As String) As Boolean Implements TipoMotorProductoService.ITipoMotorProductoService.Buscar
            Return MyBase.Channel.Buscar(pTipMot, pCodEmp)
        End Function
        
        Public Function BuscarAsync(ByVal pTipMot As String, ByVal pCodEmp As String) As System.Threading.Tasks.Task(Of Boolean) Implements TipoMotorProductoService.ITipoMotorProductoService.BuscarAsync
            Return MyBase.Channel.BuscarAsync(pTipMot, pCodEmp)
        End Function
        
        Public Function Insertar(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As Boolean Implements TipoMotorProductoService.ITipoMotorProductoService.Insertar
            Return MyBase.Channel.Insertar(Clase)
        End Function
        
        Public Function InsertarAsync(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As System.Threading.Tasks.Task(Of Boolean) Implements TipoMotorProductoService.ITipoMotorProductoService.InsertarAsync
            Return MyBase.Channel.InsertarAsync(Clase)
        End Function
        
        Public Function Actualizar(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As Boolean Implements TipoMotorProductoService.ITipoMotorProductoService.Actualizar
            Return MyBase.Channel.Actualizar(Clase)
        End Function
        
        Public Function ActualizarAsync(ByVal Clase As TipoMotorProductoService.TipoMotorProducto) As System.Threading.Tasks.Task(Of Boolean) Implements TipoMotorProductoService.ITipoMotorProductoService.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(Clase)
        End Function
        
        Public Function Borrar(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As Boolean Implements TipoMotorProductoService.ITipoMotorProductoService.Borrar
            Return MyBase.Channel.Borrar(pTipMot, pCodEmp, pCodUsu, pNomPc, pDirIp)
        End Function
        
        Public Function BorrarAsync(ByVal pTipMot As String, ByVal pCodEmp As String, ByVal pCodUsu As String, ByVal pNomPc As String, ByVal pDirIp As String) As System.Threading.Tasks.Task(Of Boolean) Implements TipoMotorProductoService.ITipoMotorProductoService.BorrarAsync
            Return MyBase.Channel.BorrarAsync(pTipMot, pCodEmp, pCodUsu, pNomPc, pDirIp)
        End Function
    End Class
End Namespace
