// Auto-generado: registro de todas las ventanas migradas desde windows (1).tsx (monolito legacy)
// hacia los archivos individuales bajo src/features/escritorio/windows/**.
//
// Uso en windows.tsx:
//   import { registerLegacyWindows } from "./windows/registryAdditions";
//   registerLegacyWindows(add, addAliases);
//
// Coloca esa llamada junto a los demas `add(...)` / `addAliases(...)`, antes del bloque
// de `legacyAliases` (para que estas 266 etiquetas ya no dependan del fallback a
// `legacyRenderWindow` / windows (1).tsx).

import type { WindowComponent } from "../windows";

import { GuiaRemision, NuevaGuia } from "@/features/escritorio/windows/Ventas/Documentos/GuiasRemision";
import { Factura } from "@/features/escritorio/windows/Ventas/Documentos/Facturas";
import { Notas, NuevaNota } from "@/features/escritorio/windows/Ventas/Documentos/Notas";
import { GuiaDevolucion } from "@/features/escritorio/windows/Ventas/Documentos/GuiasDevolucion";
import { Boleta } from "@/features/escritorio/windows/Ventas/Documentos/Boletas";
import { ResumenBoletas } from "@/features/escritorio/windows/Ventas/Documentos/ResumenDeBoletas";
import { ReporteCotizaciones } from "@/features/escritorio/windows/Ventas/Reportes/Cotizaciones";
import { ReclamoGarantia } from "@/features/escritorio/windows/Ventas/Pre y Post Venta/ReclamoGarantia";
import { SepararOrden } from "@/features/escritorio/windows/Ventas/Pre y Post Venta/SepararOrden";
import { ReporteOrdenCompra } from "@/features/escritorio/windows/Ventas/Reportes/OrdenesCompra";
import { ActualizarVendedor } from "@/features/escritorio/windows/Ventas/Pre y Post Venta/ActualizarVendedor";
import { EnviarCorreos } from "@/features/escritorio/windows/Ventas/Pre y Post Venta/EnviarCorreos";
import { Cartera } from "@/features/escritorio/windows/Ventas/Clientes/Cartera";
import { Despacho } from "@/features/escritorio/windows/Almacenes/Almacen/Despacho";
import { PrecioCliente } from "@/features/escritorio/windows/Precios/PrecioCliente";
import { PrecioOferta } from "@/features/escritorio/windows/Precios/PrecioOferta";
import { FactoresRubros } from "@/features/escritorio/windows/Precios/FactoresRubros";
import { PrecioLista } from "@/features/escritorio/windows/Precios/PrecioLista";
import { PrecioFabricantes } from "@/features/escritorio/windows/Precios/PrecioFabricantes";
import { PreciosManager } from "@/features/escritorio/windows/Precios/PreciosManager";
import { RegistroVenta } from "@/features/escritorio/windows/Ventas/Registro/RegistroVenta";
import { RegistroAuxiliar } from "@/features/escritorio/windows/Ventas/Registro/RegistroAuxiliar";
import { ResumenRegistro } from "@/features/escritorio/windows/Ventas/Registro/ResumenRegistro";
import { CtasXCobrar } from "@/features/escritorio/windows/Creditos/Consultas/CtasXCobrar";
import { Anticipos } from "@/features/escritorio/windows/Creditos/Documentos/Anticipos";
import { Planillas } from "@/features/escritorio/windows/Creditos/Documentos/Planillas";
import { Letras } from "@/features/escritorio/windows/Creditos/Documentos/Letras";
import { AprobacionCreditos } from "@/features/escritorio/windows/Creditos/Aprobaciones/Creditos";
import { PermisoUsuarioCreditos } from "@/features/escritorio/windows/Creditos/Aprobaciones/PermisoUsuario";
import { CotizTallerCredito } from "@/features/escritorio/windows/Creditos/Aprobaciones/CotizTaller";
import { RecepcionDocCreditos } from "@/features/escritorio/windows/Creditos/Aprobaciones/RecepcionDoc";
import { SaldoBancosCreditos } from "@/features/escritorio/windows/Creditos/Mantenimiento/SaldoBancos";
import { TipoCambio } from "@/features/escritorio/windows/Creditos/Mantenimiento/RenuevaTipoCambio";
import { ProcesarJob } from "@/features/escritorio/windows/Creditos/Mantenimiento/ProcesarJob";
import { VincularGR } from "@/features/escritorio/windows/Creditos/Mantenimiento/VincularGR";
import { CreditosReporteDialog } from "@/features/escritorio/windows/Reportes/CreditosReporteDialog";
import { LookupDialog } from "@/components/ui/desktop-primitives";
import { DocIngresosList, DocSalidasList, TransferenciasList } from "@/features/escritorio/windows/MovimientosAlmacen";
import { DocIngresos } from "@/features/escritorio/windows/Almacenes/Almacen/DocIngresos";
import { ChequeoFI } from "@/features/escritorio/windows/Almacenes/Almacen/ChequeoFI";
import { TransitoDocs } from "@/features/escritorio/windows/Almacenes/Transito/Documentos";
import { AtenderOT } from "@/features/escritorio/windows/Almacenes/Almacen/AtenderOT";
import { Vales } from "@/features/escritorio/windows/Almacenes/Almacen/Vales";
import { ProductosList } from "@/features/escritorio/windows/Productos";
import { LiquiGastos } from "@/features/escritorio/windows/Almacenes/Mantenimiento/LiquiGastos";
import { ActMinMax } from "@/features/escritorio/windows/Almacenes/Mantenimiento/ActMinMax";
import { UbicacionesWindow } from "@/features/escritorio/windows/Ubicaciones";
import { Tarjetas } from "@/features/escritorio/windows/Almacenes/Consultas/Tarjetas";
import { Calendario } from "@/features/escritorio/windows/Almacenes/Indicadores/Calendario";
import { ProcesarCobertura } from "@/features/escritorio/windows/Almacenes/Indicadores/ProcesarCobertura";
import { OrdenImportacion } from "@/features/escritorio/windows/Importaciones/Pedidos/OrdenImportacion";
import { CostosReporteDialog } from "@/features/escritorio/windows/Reportes/CostosReporteDialog";
import { ActivosFijos } from "@/features/escritorio/windows/Activos/Activos/ActivosFijos";
import { ReporteContainer } from "@/features/escritorio/windows/Reportes/ReporteContainer";
import { ValorizarFI } from "@/features/escritorio/windows/Contabilidad/Costos/Importaciones/ValorizarFI";
import { Recalcular } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/Recalcular";
import { CerrarMes } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/CerrarMes";
import { TrasladarCostos } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/TrasladarCostos";
import { InvRotativo } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/InvRotativo";
import { Consolidado } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/Consolidado";
import { GenerarPeriodo } from "@/features/escritorio/windows/Contabilidad/Costos/Procesos/GenerarPeriodo";
import { Asientos } from "@/features/escritorio/windows/Contabilidad/Tesoreria/Asientos";
import { MovimientoBancos } from "@/features/escritorio/windows/Contabilidad/Tesoreria/MovimientoBancos";
import { RegistroComprasList } from "@/features/escritorio/windows/ComprasRegistro";
import { CajaChica } from "@/features/escritorio/windows/Contabilidad/Caja Chica/ArqueoCaja";
import { CierreMes } from "@/features/escritorio/windows/Contabilidad/Procesos/CierreMes";
import { CuentaDestino } from "@/features/escritorio/windows/Contabilidad/Procesos/CuentaDestino";
import { DifTipoCambio } from "@/features/escritorio/windows/Contabilidad/Procesos/DifTipoCambio";
import { FlujoCaja } from "@/features/escritorio/windows/Contabilidad/Procesos/FlujoDeCaja";
import { GenerarTXT } from "@/features/escritorio/windows/Contabilidad/Procesos/GenerarTXTLibros";
import { ContabilidadReporteDialog } from "@/features/escritorio/windows/Reportes/ContabilidadReporteDialog";
import { SolicitudCompraList } from "@/features/escritorio/windows/SolicitudCompra";
import { OrdenCompraList } from "@/features/escritorio/windows/OrdenCompra";
import { SolicitudGastoList } from "@/features/escritorio/windows/SolicitudGasto";
import { PlanillaViaticosList } from "@/features/escritorio/windows/PlanillaViaticos";
import { TarifaGastoViaje } from "@/features/escritorio/windows/Compras/Control/TarifaGastoViaje";
import { TarifaTaxisCasa } from "@/features/escritorio/windows/Compras/Control/TarifaTaxisCasa";
import { TarifaTaxiDestino } from "@/features/escritorio/windows/Compras/Control/TarifaTaxiDestino";
import { CuentasPagarList } from "@/features/escritorio/windows/CuentasPagar";
import { ReportePagosCuentasXPagar } from "@/features/escritorio/windows/Compras/Reportes/PagoCuentasXPagar";
import { ReporteCtasXPagarUnidad } from "@/features/escritorio/windows/Compras/Reportes/CuentasXPagarPorUnidad";
import { PedirRepuestos } from "@/features/escritorio/windows/Servicios/Almacen/PedirRepuestos";
import { OrdenTrabajo } from "@/features/escritorio/windows/Servicios/Orden de Trabajo/OT";
import { Marcaciones } from "@/features/escritorio/windows/Servicios/Orden de Trabajo/Marcaciones";
import { GarantiaWin } from "@/features/escritorio/windows/Servicios/Garantia/OrdenReparacion";
import { Kilometraje } from "@/features/escritorio/windows/Servicios/Control Vehicular/Kilometraje";
import { OficinaUsuario } from "@/features/escritorio/windows/Servicios/Mantenimiento/OficinaUsuario";
import { ServicioReporteDialog } from "@/features/escritorio/windows/Reportes/ServicioReporteDialog";
import { PuntosControl } from "@/features/escritorio/windows/Rondas Asignacion/PuntosControlRutas";
import { TelefoniaInv } from "@/features/escritorio/windows/Telefonia/Mantenimiento/Modelos";
import { AsignaPersona } from "@/features/escritorio/windows/Telefonia/Asignacion/AsignaPersona";
import { PersonalTiempo } from "@/features/escritorio/windows/Personal/Asignaciones/Faltas";
import { MarcacionOnline } from "@/features/escritorio/windows/Personal/Asignaciones/MarcacionOnline";
import { FichaGeneral } from "@/features/escritorio/windows/Personal/Informacion/FichaGeneral";
import { PersonalReporteDialog } from "@/features/escritorio/windows/Reportes/PersonalReporteDialog";
import { CapacitacionesWin } from "@/features/escritorio/windows/Personal/Informacion/Capacitaciones";
import { PlanillaSueldos } from "@/features/escritorio/windows/Personal/Planilla Sueldos/QuintaCategoria";
import { ProcesarMarcas } from "@/features/escritorio/windows/Personal/Comunicaciones/ProcesarMarcas";
import { ClientesList } from "@/features/escritorio/windows/Clientes";
import { Modelos } from "@/features/escritorio/windows/Tablas/Almacenes/Modelos";
import { Categorias } from "@/features/escritorio/windows/Tablas/Almacenes/Categorias";
import { Partidas } from "@/features/escritorio/windows/Tablas/Importaciones/Partidas";
import { Marcas } from "@/features/escritorio/windows/Tablas/Importaciones/Marcas";
import { PlantillaRepuestos } from "@/features/escritorio/windows/Tablas/Servicios/PlantillaRepuestos";
import { PlantillaRepuestosCliente } from "@/features/escritorio/windows/Tablas/Servicios/PlantillaRepuestosCliente";
import { UbicacionServicio } from "@/features/escritorio/windows/Tablas/Servicios/UbicacionServicio";
import { Vehiculos } from "@/features/escritorio/windows/Tablas/Servicios/Vehiculos";
import { Proveedores } from "@/features/escritorio/windows/Tablas/Compras/Proveedores";
import { CondicionDePago } from "@/features/escritorio/windows/Tablas/Compras/CondicionDePago";
import { CuentaContable } from "@/features/escritorio/windows/Tablas/Contabilidad/CuentaContable";
import { CuentasDestino } from "@/features/escritorio/windows/Tablas/Contabilidad/CuentasDestino";
import { RubroPlanilla } from "@/features/escritorio/windows/Tablas/Personal/RubroPlanilla";
import { RubroPlanillaCtas } from "@/features/escritorio/windows/Tablas/Personal/RubroPlanillaCtas";
import { Horarios } from "@/features/escritorio/windows/Personal/Asignaciones/Horarios";
import { Feriados } from "@/features/escritorio/windows/Creditos/Mantenimiento/Feriados";
import { AFP } from "@/features/escritorio/windows/Tablas/Personal/AFP";
import { Cargos } from "@/features/escritorio/windows/Tablas/Personal/Cargos";
import { Areas } from "@/features/escritorio/windows/Tablas/Personal/Areas";
import { MotivosFaltas } from "@/features/escritorio/windows/Tablas/Personal/MotivosFaltas";
import { EquipoLector } from "@/features/escritorio/windows/Tablas/Personal/EquipoLector";
import { TipoHoraExtra } from "@/features/escritorio/windows/Tablas/Personal/TipoHoraExtra";
import { TipoMotores } from "@/features/escritorio/windows/Tablas/Almacenes/TipoMotores";
import { Ruteador } from "@/features/escritorio/windows/Tablas/Rondas/Ruteador";
import { Rutas } from "@/features/escritorio/windows/Tablas/Rondas/Rutas";
import { PuntosControl } from "@/features/escritorio/windows/Tablas/Rondas/PuntosControl";
import { CerrarSesion } from "@/features/escritorio/windows/Logueo Login/CerrarSesion";
import { CambiarContrasena } from "@/features/escritorio/windows/Logueo Login/CambiarContrasena";
import { CambiarEmpresa } from "@/features/escritorio/windows/Logueo Login/CambiarEmpresa";
import { UsuariosAdmin } from "@/features/escritorio/windows/Administracion/Seguridad/Usuarios";
import { Perfiles } from "@/features/escritorio/windows/Administracion/Seguridad/Perfiles";
import { Sesiones } from "@/features/escritorio/windows/Administracion/Seguridad/Sesiones";
import { AtenderSolicitud } from "@/features/escritorio/windows/Administracion/Usuarios/AtenderSolicitud";
import { IndicadoresVentaDialog } from "@/features/escritorio/windows/Almacenes/Indicadores/Tablero";
import { EncuestaWin } from "@/features/escritorio/windows/Administracion/Encuestas/Encuesta";
import { ComputadoraAsignar } from "@/features/escritorio/windows/Administracion/Inventario/AsignarComputadora";
import { ComputadoraInv } from "@/features/escritorio/windows/Administracion/Inventario/Computadora";
import { LlamadasWin } from "@/features/escritorio/windows/Administracion/Llamadas/Llamadas";
import { EquiposMarcacionPersonal } from "@/features/escritorio/windows/Administracion/Tablas Generales/EquiposMarcacionPersonal";
import { Empresas } from "@/features/escritorio/windows/Administracion/Tablas Generales/Empresas";
import { SeriesDocumentos } from "@/features/escritorio/windows/Administracion/Tablas Generales/SeriesDocumentos";
import { Locaciones } from "@/features/escritorio/windows/Administracion/Tablas Generales/Locaciones";
import { RubrosDeProductos } from "@/features/escritorio/windows/Administracion/Tablas Generales/RubrosDeProductos";
import { ParametrosLocaciones } from "@/features/escritorio/windows/Administracion/Tablas Generales/ParametrosLocaciones";
import { ParametrosPlanillaSueldos } from "@/features/escritorio/windows/Administracion/Tablas Generales/ParametrosPlanillaSueldos";
import { RubrosXEmpresa } from "@/features/escritorio/windows/Administracion/Tablas Generales/RubrosXEmpresa";
import { CrmReporteDialog } from "@/features/escritorio/windows/Reportes/CrmReporteDialog";
import { GerenciaReporteDialog } from "@/features/escritorio/windows/Reportes/GerenciaReporteDialog";
import { SolicitudSoporte } from "@/features/escritorio/windows/Ayuda/Usuario/Solicitud";
import { InfoCambios } from "@/features/escritorio/windows/Ayuda/Ayuda/InformacionCambios";
import { Acerca } from "@/features/escritorio/windows/Ayuda/Ayuda/Acerca";

type AddFn = (label: string, component: WindowComponent) => void;
type AddAliasesFn = (baseLabel: string, aliases: string[], component: WindowComponent) => void;

export function registerLegacyWindows(add: AddFn, addAliases: AddAliasesFn) {
  addAliases("Guía Remisión", ["Guías Remisión", "Guia Remision"], GuiaRemision);
  add("Nueva Guía", NuevaGuia);
  add("Factura", Factura);
  add("Notas", Notas);
  add("Nueva Nota", NuevaNota);
  add("Guía Devolución", GuiaDevolucion);
  add("Boleta", Boleta);
  add("Resumen de Boletas", ResumenBoletas);
  addAliases("Cotizaciones", ["Cotizacion", "Pre y Post Venta"], ReporteCotizaciones);
  add("Reclamo Garantía", ReclamoGarantia);
  add("Separar Orden", SepararOrden);
  addAliases("Ordenes Compra", ["Órdenes Compra"], ReporteOrdenCompra);
  add("Actualizar Vendedor", ActualizarVendedor);
  addAliases("Enviar Correos", ["Comunicaciones"], EnviarCorreos);
  add("Cartera", Cartera);
  addAliases("Despacho", ["Requisiciones", "Datos Despacho Clientes", "Despachos"], Despacho);
  add("Precios Cliente", PrecioCliente);
  add("Precio Oferta", PrecioOferta);
  addAliases("Factores Rubros", ["Factores y Descuentos"], FactoresRubros);
  add("Precio Lista", PrecioLista);
  add("Precio Fabricantes", PrecioFabricantes);
  addAliases("Precios", ["Tarifas"], (() => <PreciosManager initial="Precio Lista" />));
  add("Registro", RegistroVenta);
  add("Registro Auxiliar", RegistroAuxiliar);
  add("Resumen Registro", ResumenRegistro);
  addAliases("Ctas x Cobrar", ["Cuentas x Cobrar", "Ctas. x Cobrar"], CtasXCobrar);
  add("Anticipos", Anticipos);
  add("Planillas", Planillas);
  add("Letras", Letras);
  addAliases("Créditos", ["Creditos"], AprobacionCreditos);
  add("Permiso Usuario", PermisoUsuarioCreditos);
  add("Cotiz. Taller", CotizTallerCredito);
  addAliases("Recepcion Doc.", ["Recepción Doc."], RecepcionDocCreditos);
  add("Saldo Bancos", SaldoBancosCreditos);
  addAliases("Tipo Cambio Ventas", ["Mantenimiento Tipo de Cambio", "Renueva Tipo Cambio"], TipoCambio);
  add("Procesar Job", (() => <ProcesarJob label="Procesar Job" subtitle="Procesa y vincula documentos pendientes asociados a créditos." />));
  add("Vincular G/R", (() => <VincularGR label="Vincular G/R" subtitle="Relaciona guías de remisión con documentos comerciales y de cobranza." />));
  add("Visita Cobrador", (() => <CreditosReporteDialog label="Visita Cobrador" />));
  add("Visitas Cobrador", (() => <CreditosReporteDialog label="Visitas Cobrador" />));
  add("Detalle Vencimientos", (() => <CreditosReporteDialog label="Detalle Vencimientos" />));
  add("Acumulado Vencimientos", (() => <CreditosReporteDialog label="Acumulado Vencimientos" />));
  add("Notas Debito/Credito", (() => <CreditosReporteDialog label="Notas Debito/Credito" />));
  add("Consultas", (() => <LookupDialog title="Consultas" columns={["Código", "Descripción", "Estado", "Referencia"]} rows={10} />));
  add("Doc. Ingresos", DocIngresosList);
  add("Doc.Ingresos", DocIngresos);
  addAliases("Doc.Salidas", ["Doc. Salidas"], DocSalidasList);
  add("Chequeo F/I", ChequeoFI);
  addAliases("MTI", ["M T I", "T / I", "T/I", "Compras", "Documentos", "Anulación en Consulta"], TransitoDocs);
  addAliases("Atender OT", ["Vales / Despachos"], AtenderOT);
  add("Vales", Vales);
  add("Productos", ProductosList);
  add("Liqui. Gastos", LiquiGastos);
  add("Act. Min Max", ActMinMax);
  add("Ubicaciones", UbicacionesWindow);
  add("Tarjetas", Tarjetas);
  add("Calendario", Calendario);
  add("Procesar Cobertura", ProcesarCobertura);
  add("Transferencias", TransferenciasList);
  addAliases("Orden Importación", ["Orden de Importación", "Embarque", "Internos", "Pedido Interno", "Embarques de Importación"], OrdenImportacion);
  add("Importaciones", (() => <CostosReporteDialog label="Importaciones" />));
  add("Activos Fijos", ActivosFijos);
  add("Reporte Activos Fijos", (() => <ReporteContainer label="Reporte Activos Fijos" />));
  addAliases("Valorizar F/I", ["Ajustar Costos"], ValorizarFI);
  add("Recalcular", (() => <Recalcular label="Recalcular Costos" subtitle="Recalcula el costo promedio ponderado de todos los productos del periodo seleccionado." />));
  add("Cerrar Mes", (() => <CerrarMes label="Cerrar Mes" subtitle="Congela el mes comercial: bloquea documentos y libera datos para auditoría." />));
  add("Trasladar Costos", (() => <TrasladarCostos label="Trasladar Costos" subtitle="Transfiere costos calculados hacia contabilidad y kardex valorizado." />));
  add("Inv. Rotativo", (() => <InvRotativo label="Inventario Rotativo" subtitle="Genera muestras de conteo rotativo por categoría / ubicación." />));
  add("Consolidado", (() => <Consolidado label="Consolidado" subtitle="Consolida movimientos y saldos de todos los almacenes." />));
  add("Generar Periodo", (() => <GenerarPeriodo label="Generar Periodo" subtitle="Crea el nuevo periodo contable / comercial." />));
  add("Asientos", Asientos);
  add("Movimiento Bancos", MovimientoBancos);
  addAliases("Registro Compra", ["Recibo Honorario", "Compras y/o Gastos"], RegistroComprasList);
  add("Diario", (() => <ReporteContainer label="Libro Diario" />));
  addAliases("Provisional", ["Reembolso", "Arqueo Caja"], CajaChica);
  add("Cierre Mes", (() => <CierreMes label="Cierre Mes" subtitle="Cierre contable mensual con validación de saldos cuadrados." />));
  add("Cuenta Destino", (() => <CuentaDestino label="Cuenta Destino" subtitle="Reasigna asientos entre cuentas contables destino." />));
  add("Dif. Tipo Cambio", (() => <DifTipoCambio label="Diferencia de Tipo de Cambio" subtitle="Calcula pérdidas / ganancias por diferencia en tipo de cambio del periodo." />));
  add("Flujo de Caja", FlujoCaja);
  add("Generar TXT Libros", GenerarTXT);
  add("Libro Diario", (() => <ContabilidadReporteDialog label="Libro Diario" />));
  add("Libro Mayor", (() => <ContabilidadReporteDialog label="Libro Mayor" />));
  add("Caja y Bancos", (() => <ContabilidadReporteDialog label="Caja y Bancos" />));
  add("Registro de Compras", (() => <ContabilidadReporteDialog label="Registro de Compras" />));
  addAliases("Solicitud de Compra", ["Solicitud Compra"], SolicitudCompraList);
  addAliases("Orden de Compra", ["Orden Compra"], OrdenCompraList);
  addAliases("Solicitud Gasto", ["Solicitud Gastos"], SolicitudGastoList);
  addAliases("Planilla Viático", ["Planilla Viáticos", "Planilla Viatico"], PlanillaViaticosList);
  add("Tarifa Gasto Viaje", (() => <TarifaGastoViaje label="Tarifa Gasto Viaje" columns={["Ruta", "Categoría", "Moneda", "Tarifa", "Estado"]} />));
  add("Tarifa Taxis Casa", (() => <TarifaTaxisCasa label="Tarifa Taxis Casa" columns={["Zona", "Horario", "Moneda", "Tarifa", "Estado"]} />));
  add("Tarifas Taxi Destino", (() => <TarifaTaxiDestino label="Tarifas Taxi Destino" columns={["Destino", "Tipo", "Moneda", "Tarifa", "Estado"]} />));
  addAliases("Cuentas x Pagar", ["Ctas x Pagar"], CuentasPagarList);
  add("Pagos Cuentas x Pagar", ReportePagosCuentasXPagar);
  add("Cuentas x Pagar Por Unidad", ReporteCtasXPagarUnidad);
  add("Pedir Repuestos", PedirRepuestos);
  addAliases("Solicitud OT", ["OT", "Orden de Trabajo", "Gastos Reales"], OrdenTrabajo);
  add("Marcaciones", (() => <Marcaciones title="Marcaciones — OT" />));
  addAliases("Pre Marcacion", ["Pre Marcación"], (() => <Marcaciones title="Pre Marcación — OT" />));
  add("Marcar OT", (() => <Marcaciones title="Marcar OT" />));
  add("Orden Reparación", (() => <GarantiaWin title="Orden de Reparación" />));
  add("Reclamo Cliente", (() => <GarantiaWin title="Reclamo Cliente" />));
  addAliases("Garantía", ["Garantia"], (() => <GarantiaWin title="Garantía" />));
  addAliases("Control Vehicular", ["Kilometraje"], Kilometraje);
  addAliases("Mantenimiento", ["Oficina Usuario"], OficinaUsuario);
  add("Gastos Detallado", (() => <ServicioReporteDialog label="Gastos Detallado" />));
  add("Gastos Detalle", (() => <ServicioReporteDialog label="Gastos Detalle" />));
  add("Liquidación x Garantia", (() => <ServicioReporteDialog label="Liquidación x Garantia" />));
  add("LiquidaciÃ³n x Garantia", (() => <ServicioReporteDialog label="LiquidaciÃ³n x Garantia" />));
  add("Puntos Control Rutas", (() => <PuntosControl title="Puntos de Control" />));
  add("Rondas", (() => <PuntosControl title="Rondas" />));
  add("Ruteador Rutas", (() => <PuntosControl title="Ruteador de Rutas" />));
  add("Modelos", (() => <TelefoniaInv title="Modelos" />));
  add("Planes", (() => <TelefoniaInv title="Planes" />));
  addAliases("Líneas", ["Lineas"], (() => <TelefoniaInv title="Líneas" />));
  add("Equipos", (() => <TelefoniaInv title="Equipos" />));
  add("Asigna Persona", AsignaPersona);
  add("Faltas", (() => <PersonalTiempo title="Faltas" />));
  addAliases("Asigna H. Extra", ["Asig. H. Extra"], (() => <PersonalTiempo title="Asignación H. Extra" />));
  add("Horas Extras", (() => <PersonalTiempo title="Horas Extras" />));
  add("Descuentos", (() => <PersonalTiempo title="Descuentos" />));
  add("Recursos", (() => <PersonalTiempo title="Recursos" />));
  addAliases("Marcación Online", ["Marcacion Online", "Marcación", "Marcacion", "Admin. Lector"], MarcacionOnline);
  add("Horarios", (() => <PersonalTiempo title="Horarios / Turnos" />));
  add("Ingresos", (() => <PersonalTiempo title="Ingresos" />));
  addAliases("Jefe Área", ["Jefe Area"], (() => <PersonalTiempo title="Jefe de Área" />));
  add("Cronograma Mina", (() => <PersonalTiempo title="Cronograma Mina" />));
  addAliases("Informacion", ["Ficha General"], FichaGeneral);
  add("Personal", (() => <PersonalReporteDialog label="Personal" />));
  add("Capacitaciones", (() => <CapacitacionesWin title="Capacitaciones" />));
  add("Vacaciones", (() => <CapacitacionesWin title="Vacaciones" />));
  add("Evaluaciones", (() => <CapacitacionesWin title="Evaluaciones de Desempeño" />));
  addAliases("Quinta Categoría", ["Quinta Categoria", "Planilla Sueldos"], PlanillaSueldos);
  add("Procesar Marcas", ProcesarMarcas);
  add("Clientes", ClientesList);
  add("Modelos ", (() => <Modelos label="Modelos" columns={["Código", "Modelo", "Marca", "Estado"]} />));
  addAliases("Categorías", ["Categorias"], (() => <Categorias label="Categorías" columns={["Código", "Categoría", "Rubro", "Estado"]} />));
  add("Partidas", (() => <Partidas label="Partidas Arancelarias" columns={["Partida", "Descripción", "Ad Valorem", "Estado"]} />));
  add("Marcas", (() => <Marcas label="Marcas" columns={["Código", "Marca", "Origen", "Estado"]} />));
  addAliases("Plantillas Repuestos", ["Plantilla Repuestos"], (() => <PlantillaRepuestos label="Plantillas de Repuestos" columns={["Código", "Plantilla", "Modelo", "Nº items", "Estado"]} />));
  add("Plantilla Repuestos Cliente", (() => <PlantillaRepuestosCliente label="Plantillas de Repuestos por Cliente" columns={["Cliente", "Plantilla", "Modelo", "Vigencia", "Estado"]} />));
  add("Ubicacion Servicio", (() => <UbicacionServicio label="Ubicación de Servicio" columns={["Código", "Ubicación", "Sede", "Responsable", "Estado"]} />));
  addAliases("Vehículos", ["Vehiculos"], (() => <Vehiculos label="Vehículos" columns={["Placa", "Marca", "Modelo", "Año", "Cliente", "Estado"]} />));
  add("Proveedores", (() => <Proveedores label="Proveedores" columns={["RUC", "Razón Social", "Dirección", "Contacto", "Teléfono", "Estado"]} />));
  addAliases("Condición de Pago", ["CondiciÃ³n de Pago"], (() => <CondicionDePago label="Condición de Pago" columns={["Código", "Descripción", "Días", "Tipo", "Estado"]} />));
  add("Cuenta Contable", (() => <CuentaContable label="Cuentas Contables" columns={["Cuenta", "Descripción", "Naturaleza", "Nivel", "Estado"]} />));
  add("Cuentas Destino", (() => <CuentasDestino label="Cuentas Destino" columns={["Cuenta", "Destino", "Módulo", "Estado"]} />));
  add("Rubro Planilla", (() => <RubroPlanilla label="Rubros de Planilla" columns={["Código", "Rubro", "Tipo", "Afecta", "Estado"]} />));
  add("Rubro Planilla Ctas", (() => <RubroPlanillaCtas title="Rubro Planilla Ctas" columns={["Rubro", "Cuenta Debe", "Cuenta Haber", "Estado"]} />));
  add("Horarios ", (() => <Horarios label="Horarios" columns={["Código", "Horario", "Entrada", "Salida", "Tolerancia", "Estado"]} />));
  add("Feriados", (() => <Feriados label="Feriados" columns={["Fecha", "Descripción", "Tipo", "Ámbito", "Estado"]} />));
  add("AFP", (() => <AFP label="AFP" columns={["Código", "AFP", "Comisión %", "Prima %", "Aporte %", "Estado"]} />));
  add("Cargos", (() => <Cargos label="Cargos" columns={["Código", "Cargo", "Área", "Nivel", "Estado"]} />));
  addAliases("Áreas", ["Areas"], (() => <Areas label="Áreas" columns={["Código", "Área", "Responsable", "Estado"]} />));
  add("Motivos Faltas", (() => <MotivosFaltas label="Motivos de Faltas" columns={["Código", "Motivo", "Justificada", "Descuenta", "Estado"]} />));
  add("Equipo Lector", (() => <EquipoLector label="Equipos Lectores (Biométricos)" columns={["Serie", "Marca", "IP", "Sede", "Estado"]} />));
  add("Tipo Hora Extra", (() => <TipoHoraExtra label="Tipo Hora Extra" columns={["Código", "Tipo", "Factor", "Máximo", "Estado"]} />));
  add("Tipo Motores", (() => <TipoMotores label="Tipo Motores" columns={["Código", "Tipo", "Marca", "Estado"]} />));
  add("Ruteador", (() => <Ruteador label="Ruteadores de Rondas" columns={["Código", "Ruteador", "Zona", "Estado"]} />));
  add("Rutas", (() => <Rutas label="Rutas" columns={["Código", "Ruta", "Zona", "Nº puntos", "Estado"]} />));
  add("Puntos Control", (() => <PuntosControl label="Puntos de Control" columns={["Código", "Punto", "Dirección", "Ruta", "Estado"]} />));
  addAliases("Cerrar Sesión", ["Cerrar Sesion"], CerrarSesion);
  addAliases("Cambiar Contraseña", ["Cambiar Contrasena"], CambiarContrasena);
  add("Cambiar Empresa", CambiarEmpresa);
  add("Usuarios", UsuariosAdmin);
  add("Perfiles", Perfiles);
  add("Sesiones", Sesiones);
  add("Atender Solicitud", AtenderSolicitud);
  add("Tablero", IndicadoresVentaDialog);
  add("Indicadores", (() => <EncuestaWin title="Indicadores de Encuesta" />));
  add("Encuesta", (() => <EncuestaWin title="Encuesta" />));
  add("Resultado", (() => <ReporteContainer label="Resultados de Encuesta" />));
  add("Asignar Computadora", ComputadoraAsignar);
  add("Computadora", ComputadoraInv);
  add("Llamadas", LlamadasWin);
  add("Equipos Marcación Personal", (() => <EquiposMarcacionPersonal title="Equipos Marcación Personal" columns={["Serie", "IP", "Sede", "Modelo", "Estado"]} />));
  add("Empresas", (() => <Empresas title="Empresas" columns={["RUC", "Razón Social", "Sucursal", "Régimen", "Estado"]} />));
  add("Series Documentos", (() => <SeriesDocumentos title="Series de Documentos" columns={["Tipo Doc.", "Serie", "Correlativo", "Sede", "Estado"]} />));
  add("Locaciones", (() => <Locaciones title="Locaciones / Sedes" columns={["Código", "Locación", "Dirección", "Ubigeo", "Estado"]} />));
  add("Rubros de Productos", (() => <RubrosDeProductos title="Rubros de Productos" columns={["Código", "Rubro", "Cuenta contable", "Estado"]} />));
  addAliases("Parámetros Locaciones", ["Parametros Locaciones"], (() => <ParametrosLocaciones title="Parámetros de Locaciones" columns={["Locación", "Parámetro", "Valor", "Descripción"]} />));
  addAliases("Parámetros Planilla Sueldos", ["Parametros Planilla Sueldos"], (() => <ParametrosPlanillaSueldos title="Parámetros Planilla de Sueldos" columns={["Parámetro", "Valor", "Vigente desde", "Descripción"]} />));
  add("Rubros x Empresa", (() => <RubrosXEmpresa title="Rubros por Empresa" columns={["Empresa", "Rubro", "Cuenta", "Estado"]} />));
  add("Oportunidad Negocio", (() => <CrmReporteDialog label="Oportunidad Negocio" />));
  add("Tarjeta Cliente", (() => <CrmReporteDialog label="Tarjeta Cliente" />));
  add("Cuota Vendedor", (() => <CrmReporteDialog label="Cuota Vendedor" />));
  add("Ocurrencias", (() => <CrmReporteDialog label="Ocurrencias" />));
  add("Visita Clientes", (() => <CrmReporteDialog label="Visita Clientes" />));
  add("000 - Ventas", (() => <GerenciaReporteDialog label="000 - Ventas" />));
  add("010 - Importaciones", (() => <GerenciaReporteDialog label="010 - Importaciones" />));
  add("020 - Inventario y Costos", (() => <GerenciaReporteDialog label="020 - Inventario y Costos" />));
  add("030 - Contabilidad", (() => <GerenciaReporteDialog label="030 - Contabilidad" />));
  add("040 - Creditos y Cobranzas", (() => <GerenciaReporteDialog label="040 - Creditos y Cobranzas" />));
  add("Datos para Indicadores", (() => <GerenciaReporteDialog label="Datos para Indicadores" />));
  add("Tarjeta", (() => <GerenciaReporteDialog label="Tarjeta" />));
  add("Contenedor Reportes", (() => <GerenciaReporteDialog label="Contenedor Reportes" />));
  add("Estados Financieros", (() => <GerenciaReporteDialog label="Estados Financieros" />));
  add("Solicitud", SolicitudSoporte);
  addAliases("Información Cambios", ["Informacion Cambios"], InfoCambios);
  add("Acerca", Acerca);
}
